# Makefile.custom --
#
# This makefile is loaded  by "Makefile".  Its purpose is to
# hold user customisable variables.

#page
## ------------------------------------------------------------
## Installation directories.
## ------------------------------------------------------------

ikarus_PREFIX		= /usr/local
ikarus_BINDIR		= ${ikarus_PREFIX}/bin
ikarus_LIBDIR		= ${ikarus_PREFIX}/lib
ikarus_PKGLIBDIR	= ${ikarus_LIBDIR}/ikarus

## ------------------------------------------------------------

prefix			= $(ikarus_PREFIX)
bindir			= $(ikarus_BINDIR)
libdir			= $(ikarus_LIBDIR)
pkglibdir		= $(ikarus_PKGLIBDIR)

## ------------------------------------------------------------


### end of file
# Local Variables:
# mode: makefile
# fill-column: 60
# End:
