# Makefile.custom --
#
# This makefile is loaded  by "Makefile".  Its purpose is to
# hold user customisable variables.

#page
## ------------------------------------------------------------
## Data.
## ------------------------------------------------------------

# The list  of completion  modules to include.   Each string
# must be the prefix of a '*_completions' file in the source
# directory.
MODULES		= ikarus ffi srfi_streams srfi_list

## ------------------------------------------------------------

#page
## ------------------------------------------------------------
## Wrapper installation directories.
## ------------------------------------------------------------

prefix		= $(HOME)
bindir		= $(prefix)/bin
datadir		= $(prefix)/share
#pkgdatadir	= $(datadir)/ikarus
pkgdatadir	= $(prefix)

## ------------------------------------------------------------

#page
## ------------------------------------------------------------
## Ikarus installation directories.
## ------------------------------------------------------------

IKARUS_PREFIX		= /usr/local
IKARUS_BINDIR		= ${IKARUS_PREFIX}/bin
IKARUS_LIBDIR		= ${IKARUS_PREFIX}/lib
IKARUS_PKGLIBDIR	= ${IKARUS_LIBDIR}/ikarus


### end of file
# Local Variables:
# mode: makefile
# fill-column: 60
# End:
