\input texinfo.tex
@c %**start of header
@setfilename nausicaa-postgresql.info
@settitle PostgreSQL for Nausicaa
@c %**end of header

@c page
@c ------------------------------------------------------------
@c Macros.
@c ------------------------------------------------------------

@include version.texiinc

@c ------------------------------------------------------------
@c License macros.
@c ------------------------------------------------------------

@macro gnu{}
@acronym{GNU}
@end macro

@macro gpl{}
@acronym{GPL}
@end macro

@macro fdl{}
@acronym{FDL}
@end macro

@c ------------------------------------------------------------
@c Special notes.
@c ------------------------------------------------------------

@macro forunix{}
@strong{Unix:}
@end macro

@macro fixme{TEXT}
@strong{FIXME: \TEXT\}
@end macro

@c ------------------------------------------------------------
@c Scheme related macros.
@c ------------------------------------------------------------

@macro rnrs{VERSION}
@acronym{R\VERSION\RS}
@end macro

@macro rsix{}
Revised^6 Report on the algorithmic language Scheme
@end macro

@macro repl{}
@acronym{REPL}
@end macro

@macro srfi{}
@acronym{SRFI}
@end macro

@c Separating the @srfi{} macro from the number with a '--' rather than
@c a '-'  makes the expansion look  ugly in menu entries  under the Info
@c reader.  IMHO  this should not happen,  but it does; so  we live with
@c this, because the main purpose of this document is to provide an Info
@c version.
@macro ansrfi{NUM}
@srfi{}-\NUM\
@end macro

@macro clos{}
@acronym{CLOS}
@end macro

@macro library{SPEC}
@code{(\SPEC\)}
@end macro

@macro ffi{}
@acronym{FFI}
@end macro

@macro class{NAME}
@code{<\NAME\>}
@end macro

@macro condition{NAME}
@code{&\NAME\}
@end macro

@c ------------------------------------------------------------
@c Miscellaneous acronyms.
@c ------------------------------------------------------------

@macro ansi{}
@acronym{ANSI}
@end macro

@macro api{}
@acronym{API}
@end macro

@c Remember that @url is already used by Texinfo.
@macro aurl{}
@acronym{URL}
@end macro

@macro ascii{}
@acronym{ASCII}
@end macro

@macro cpu{}
@acronym{CPU}
@end macro

@macro csv{}
@acronym{CSV}
@end macro

@macro ieee{}
@acronym{IEEE}
@end macro

@macro iso{}
@acronym{ISO}
@end macro

@macro posix{}
@acronym{POSIX}
@end macro

@macro rfc{}
@acronym{RFC}
@end macro

@macro sql{}
@acronym{SQL}
@end macro

@macro utf{}
@acronym{UTF}
@end macro

@macro utc{}
@acronym{UTC}
@end macro

@macro tai{}
@acronym{TAI}
@end macro

@macro axml{}
@acronym{XML}
@end macro

@c ------------------------------------------------------------
@c Software acronyms.
@c ------------------------------------------------------------

@macro gmp{}
@acronym{GMP}
@end macro

@macro gcc{}
@acronym{GCC}
@end macro

@macro pg{}
PostgreSQL
@end macro

@c ------------------------------------------------------------
@c Network related acronyms.
@c ------------------------------------------------------------

@macro http{}
@acronym{HTTP}
@end macro

@macro ftp{}
@acronym{FTP}
@end macro

@macro ip{}
@acronym{IP}
@end macro

@macro ssh{}
@acronym{SSH}
@end macro

@macro ssl{}
@acronym{SSL}
@end macro

@macro tcp{}
@acronym{TCP}
@end macro

@macro tls{}
@acronym{TLS}
@end macro

@macro udp{}
@acronym{UDP}
@end macro

@macro smtp{}
@acronym{SMTP}
@end macro

@c ------------------------------------------------------------
@c Scheme language macros.
@c ------------------------------------------------------------

@macro func{NAME}
@code{\NAME\}
@end macro

@macro snull{}
@code{()}
@end macro

@macro true{}
@code{#t}
@end macro

@macro false{}
@code{#f}
@end macro

@macro keyword{NAME}
@code{#:\NAME\}
@end macro

@c ------------------------------------------------------------
@c C language macros.
@c ------------------------------------------------------------

@macro cfunc{NAME}
@code{\NAME\()}
@end macro

@macro cnull{}
@code{NULL}
@end macro

@c ------------------------------------------------------------
@c Macros for references to external documents.
@c ------------------------------------------------------------

@macro glibcref{NODE, TITLE}
@ref{\NODE\,\TITLE\,\TITLE\,libc}
@end macro

@c @macro rsixref{NODE, TITLE}
@c @ref{\NODE\,\TITLE\,\TITLE\,r6rs}
@c @end macro

@macro bibref{TAG}
@code{[\TAG\]}
@end macro

@macro autoconfref{NODE, TITLE}
@ref{\NODE\,\TITLE\,\TITLE\,autoconf}
@end macro

@macro nauref{NODE, TITLE}
@ref{\NODE\,\TITLE\,\TITLE\,nausicaa}
@end macro

@c ------------------------------------------------------------
@c RNRS document macros.
@c ------------------------------------------------------------

@macro rsixlibrary{THING}
@code{(rnrs \THING\ (6))}
@end macro

@macro arbno{THING}
\THING\*
@end macro

@macro atleastone{THING}
\THING\+
@end macro

@c ------------------------------------------------------------
@c To be used in normal text.

@macro meta{THING}
<\THING\>
@end macro

@macro metai{THING}
<\THING\1>
@end macro

@macro metaii{THING}
<\THING\2>
@end macro

@macro metaiii{THING}
<\THING\3>
@end macro

@c ------------------------------------------------------------
@c To be used inside @example environment and @samp directives.

@macro cmeta{THING}
<\THING\>
@end macro

@macro cmetai{THING}
<\THING\1>
@end macro

@macro cmetaii{THING}
<\THING\2>
@end macro

@macro cmetaiii{THING}
<\THING\3>
@end macro

@c ------------------------------------------------------------
@c To be used inside argument lists.

@macro ameta{THING}
<\THING\>
@end macro

@macro ametai{THING}
<\THING\1>
@end macro

@macro ametaii{THING}
<\THING\2>
@end macro

@macro ametaiii{THING}
<\THING\3>
@end macro

@c ------------------------------------------------------------

@macro hyper{THING}
<\THING\>
@end macro

@macro hyperi{THING}
<\THING\1>
@end macro

@macro hyperii{THING}
<\THING\2>
@end macro

@macro hyperiii{THING}
<\THING\3>
@end macro

@macro hypern{THING}
<\THING\n>
@end macro

@c ------------------------------------------------------------

@macro varo{THING}
@var{\THING\0}
@end macro

@macro vari{THING}
@var{\THING\1}
@end macro

@macro varii{THING}
@var{\THING\2}
@end macro

@macro variii{THING}
@var{\THING\3}
@end macro

@macro variv{THING}
@var{\THING\4}
@end macro

@macro varn{THING}
@var{\THING\n}
@end macro

@macro vark{THING}
@var{\THING\k}
@end macro

@macro varj{THING}
@var{\THING\j}
@end macro


@c page
@c ------------------------------------------------------------
@c Values.
@c ------------------------------------------------------------

@set TITLE                      @pg{} for Nausicaa

@c To be used as @value{PACKAGE} whenever we need to include the full
@c name of this package.
@set PACKAGE                    Nausicaa/@pg{}

@c To be used as @value{PACKAGE_NICKNAME} whenever we need to include
@c the nickname of the project: the name that is used to compose the
@c distribution tarball or the web address.
@set PACKAGE_NICKNAME           nausicaa-postgresql

@c To be used as @value{AUTHOR} whenever we need to include the list of
@c authors of this document.
@set AUTHOR                     Marco Maggi

@c To be used as @value{AUTHOR_EMAIL} whenever we need to include the
@c email of the *single* author of this document.
@set AUTHOR_EMAIL               @email{marco.maggi-ipsu@@poste.it}

@c To be used as @value{COPYRIGHT_YEARS} whenever we need to include the
@c list of copyright years.
@set COPYRIGHT_YEARS            2010

@c page
@c ------------------------------------------------------------
@c Copyright notice.
@c ------------------------------------------------------------

@copying
@noindent
This document describes version @version{} of @value{PACKAGE}, a
distribution of libraries for @rnrs{6} Scheme implementations; it
provides a binding to the Libpq C language library, a client @api{} for
@pg{} databases.  It is built upon Nausicaa/Scheme, making use of its
foreign--functions interface.

The libraries support Ikarus, Mosh and Ypsilon Scheme; the package
supports @gnu{}+Linux systems.

The package is distributed under the terms of the @gnu{} General Public
License (@gpl{}) and can be downloaded from:

@center @url{http://github.com/marcomaggi/nausicaa/downloads}

@noindent
the project home page of Nausicaa is at:

@center @url{http://marcomaggi.github.com/nausicaa.html}

@noindent
development of Nausicaa takes place at:

@center @url{http://github.com/marcomaggi/nausicaa/tree/master}

@noindent
@pg{} is available at:

@center @url{http://www.postgresql.org/}

@noindent
Copyright @copyright{} @value{COPYRIGHT_YEARS} by @value{AUTHOR} @value{AUTHOR_EMAIL}

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the @gnu{} Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with
Invariant Sections being ``@gnu{} Free Documentation License'' and
``@gnu{} General Public License'', no Front--Cover Texts, and no
Back--Cover Texts.  A copy of the license is included in the section
entitled ``@gnu{} Free Documentation License''.
@end quotation
@end copying

@c page
@c ------------------------------------------------------------
@c Headers.
@c ------------------------------------------------------------

@titlepage
@title @value{TITLE}
@subtitle Revision @version{}
@author @value{AUTHOR} @value{AUTHOR_EMAIL}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ------------------------------------------------------------

@ifinfo
@dircategory Development
@direntry
* nausicaa-postgresql: (nausicaa-postgresql).   @pg{} for Nausicaa.
@end direntry
@end ifinfo

@c ------------------------------------------------------------

@ignore
@syncodeindex tp cp
@syncodeindex vr cp
@syncodeindex fn cp
@end ignore

@c page
@ifnottex
@node Top
@top @value{TITLE}

@insertcopying

@menu
* overview::                    Overview of the package.
* typedefs::                    Object type definitions.
* enumerations::                Enumeration type definitions.
* conditions::                  Condition object definitions.
* connect::                     Connecting to a database.
* inspect::                     Inspection.
* primitives::                  Miscellaneous primitive bindings.
* compensations::               Compensated constructors.

Appendices

* Package License::             GNU General Public License.
* Documentation License::       GNU Free Documentation License.
* references::                  Bibliography and references.

Indexes

* concept index::               An entry for each concept.
* function index::              An entry for each function.
* variable index::              An entry for each variable.
* type index::                  An entry for each type.

@detailmenu
 --- The Detailed Node Listing ---

Object type definitions

* typedefs connection::         Database connection object.
* typedefs fd::                 File descriptor object.
* typedefs option::             Connection option object.

Enumeration type definitions

* enumerations connect::        Connection status.
* enumerations polling::        Polling status.

Condition object definitions

* conditions connect::          Database connection object.
* conditions error::            Error condition object.

Connecting to a database

* connect sync::                Connecting synchronously.
* connect async::               Connecting asynchronously.
* connect misc::                Other connect--related functions.

@end detailmenu
@end menu

@end ifnottex

@c page
@node overview
@chapter Overview of the package


This document describes version @version{} of @value{PACKAGE}, a
distribution of libraries for @rnrs{6} Scheme implementations; it
provides a binding to the Libpq C language library, a client @api{} for
@pg{} databases.  It is built upon Nausicaa/Scheme, making use of its
foreign--functions interface.

The libraries support Ikarus, Mosh and Ypsilon Scheme; the package
supports @gnu{}+Linux systems.

The installed libraries are:

@table @library
@item foreign databases postgresql shared-object
Exports the single binding @code{postgresql-shared-object} which
references the foreign shared library.

@item foreign databases postgresql sizeof
Exports bindings to constant values and data structures accessors.

@item foreign databases postgresql typedefs
Exports bindings for record type definitions.

@item foreign databases postgresql conditions
Exports bindings for condition object type definitions.

@item foreign databases postgresql enumerations
Exports bindings for enumeration type definitions.

@item foreign databases postgresql platform
Exports one binding for each foreign function; the bindings to the
Scheme function callouts have the same name of the C functions, so
@cfunc{PQconnectStart} is available as @func{PQconnectStart}.  This
library makes the original @pg{} documentation relevant for this
package.

@item foreign databases postgresql primitives
Exports one binding for each foreign function, implementing, for some
functions, marshaling of arguments and return values.  The bindings to
the Scheme functions have heavily modified names, for example
@cfunc{PQconnectStart} is available as @func{connect-start}; the
@samp{PQ} and @samp{pg} prefixes are always stripped, so it is suggested
to import this library with the @samp{pg:} prefix.

This document describes the @code{primitives} @api{} giving a brief
description for each function, we have to refer to the original
documentation for the true description; only the functions implementing
marshaling of values are documented: if a function is not documented, it
means that it is reexported ``as is'' from the @code{platform} library.
@ref{primitives} for the list of undocumented functions and the name
change.

@item foreign databases postgresql
Compound library exporting the high--level @api{}; it reexports bindings
from the @samp{primitives}, @samp{typedefs}, @samp{enumeration} and
@samp{conditions} libraries and the constant values from the
@samp{sizeof} library.

@item foreign databases postgresql compensated
Exports bindings to constructor functions making use of the
@library{compensations} library from Nausicaa/Scheme.
@nauref{compensations, Compensation stacks}.
@end table

@c page
@node typedefs
@chapter Object type definitions


The bindings documented in this chapter are exported by the
@library{foreign databases postgresql typedefs} library and reexported
by the @library{foreign databases postgresql} library.  It is suggested
to import these libraries by prefixing the bindings, for example with
@code{pg:}.

@menu
* typedefs connection::         Database connection object.
* typedefs fd::                 File descriptor object.
* typedefs option::             Connection option object.
@end menu

@c page
@node typedefs connection
@section Database connection object


@deftp {Record Type Name} <connection>
@deftpx {Record Type Descriptor} <connection-rtd>
Record type used to tag pointer objects referencing database
connections.  @nauref{ffi pointers, Pointer objects}.
@end deftp


@defun <connection>? @var{obj}
Return @true{} if @var{obj} is a record of type @class{connection}.
@end defun


@defun pointer-><connection> @var{pointer}
@defunx <connection>->pointer @var{conn}
Convert to and from a pointer object and a record of type
@class{connection}.
@end defun

@c page
@node typedefs fd
@section File descriptor object


@deftp {Record Type Name} <fd>
Record type used to tag exact integers representing file descriptors.
This type is compatible with the same defined by the Nausicaa/@posix{}
package.
@end deftp


@defun <fd>? @var{obj}
Return @true{} if @var{obj} is an object of type @class{fd}.
@end defun


@defun integer-><fd> @var{integer}
@defunx <fd>->integer @var{fd}
Convert to and from objects of type @class{fd} and the associated exact
integers.
@end defun

@c page
@node typedefs option
@section Connection option object


@deftp {Record Type Name} <connect-option>
@deftpx {Record Type Descriptor} <connect-option-rtd>
Record type used to mirror structures of type @code{PQconninfoOption}.
It has the following immutable fields:

@table @code
@item keyword
The keyword of the option.  A Scheme string.

@item envvar
Fallback environment variable name.  A Scheme string.

@item compiled
Fallback compiled--in default value.  A Scheme string or @false{} if the
value is not set.

@item val
Option's current value.  A Scheme string or @false{} if the value is not
set.

@item label
Label for field in connect dialog.  A Scheme string.

@item dispchar
Indicates how to display this field in a connect dialog.  A Scheme
string.

@item dispsize
Field size in characters for dialog.  An exact intger.
@end table
@end deftp


@defun make-<connect-option>
@defunx <connect-option>? @var{obj}
Constructor and predicate for records of type @class{connect-option}.
@end defun


@defun <connect-option>-keyword @var{option}
@defunx <connect-option>-envvar @var{option}
@defunx <connect-option>-compiled @var{option}
@defunx <connect-option>-val @var{option}
@defunx <connect-option>-label @var{option}
@defunx <connect-option>-dispchar @var{option}
@defunx <connect-option>-dispsize @var{option}
Accessors for the fields of records of type @class{connect-option}.
@end defun


@defun pointer-><connect-option> @var{pointer}
Given a pointer object to a structure of type @code{PQconninfoOption}
build and return a record of type @class{connect-option} initialised
with values from the structure.
@end defun

@c page
@node enumerations
@chapter Enumeration type definitions


The bindings documented in this chapter are exported by the
@library{foreign databases postgresql enumerations} library and
reexported by the @library{foreign databases postgresql} library.  It is
suggested to import these libraries by prefixing the bindings, for
example with @code{pg:}.

@menu
* enumerations connect::        Connection status.
* enumerations polling::        Polling status.
@end menu

@c page
@node enumerations connect
@section Connection status


@deftp {Enumeration Type} enum-connection-status
Enumeration type representing the current status of a @class{connection}
object.  It holds the following symbols:

@example
ok                      bad
started                 made
awaiting-response       auth-ok
setenv                  ssl-startup
needed
@end example
@end deftp


@deffn Syntax connection-status @ameta{symbol}
Expand in an enumeration set of type @code{enum-connection-status}
holding the argument symbol.
@end deffn


@defun value->connection-status @var{integer}
@defunx connection-status->value @var{enum-set}
Convert to and from exact integers and enumeration sets of type
@code{enum-connection-status}.
@end defun

@c page
@node enumerations polling
@section Polling status


@deftp {Enumeration Type} enum-polling-status
Enumeration type representing the result of polling operations performed
with @func{connect-poll}.  It holds the following symbols:

@example
ok      failed
reading writing active
@end example
@end deftp


@deffn Syntax polling-status @ameta{symbol}
Expand in an enumeration set of type @code{enum-polling-status} holding
the argument symbol.
@end deffn


@defun value->polling-status @var{integer}
@defunx polling-status->value @var{enum-set}
Convert to and from exact integers and enumeration sets of type
@code{enum-polling-status}.
@end defun

@c page
@node conditions
@chapter Condition object definitions


The bindings documented in this chapter are exported by the
@library{foreign databases postgresql conditions} library and reexported
by the @library{foreign databases postgresql} library.  It is suggested
to import these libraries by prefixing the bindings, for example with
@code{pg:}.

@menu
* conditions connect::          Database connection object.
* conditions error::            Error condition object.
@end menu

@c page
@node conditions connect
@section Database connection object


@deftp {Condition Type} &connection
Condition object type used to hold objects of type @class{connection}
which were involved in an exception; it is derived from
@condition{condition}.  It has the following fields:

@table @code
@item connection
The @class{connection} object.
@end table
@end deftp


@defun make-connection-condition @var{conn}
@defunx connection-condition? @var{obj}.
Constructor and predicate for condition objects of type
@condition{connection}.
@end defun


@defun connection-condition @var{condition}
Accessor for the field of condition objects of type
@condition{connection}.
@end defun

@c page
@node conditions error
@section Error condition object


@deftp {Condition Type} &postgresql-error
Base condition type used to tag compound condition objects associated to
@value{PACKAGE}; it is derived from @condition{error}.  It has the
following fields:

@table @code
@item code
A numeric code representing the error.
@end table
@end deftp


@defun make-postgresql-error-condition @var{code}
@defunx postgresql-error-condition? @var{obj}
Constructor and predicate for condition objects of type
@condition{postgresql-error}.
@end defun


@defun condition-postgresql-error-code @var{condition}
Accessor for the field of condition objects of type
@condition{postgresql-error}.
@end defun

@c page
@node connect
@chapter Connecting to a database


The bindings documented in this chapter are exported by the
@library{foreign databases postgresql primitives} library and reexported
by the @library{foreign databases postgresql} library.  It is suggested
to import these libraries by prefixing the bindings, for example with
@code{pg:}.

@menu
* connect sync::                Connecting synchronously.
* connect async::               Connecting asynchronously.
* connect misc::                Other connect--related functions.
@end menu

@c page
@node connect sync
@section Connecting synchronously


In the following descriptions, the @var{conn} argument is always a
Scheme object of type @class{connection}.


@defun connect-db
@defunx connect-db @var{connect-info}
@findex @func{PQconnectdb}
Wrapper for @func{PQconnectdb}.  Connect to a database according to the
parameters in the Scheme string @var{connect-info}, or the default
parameters when the string is not given; it is the simpler method to
open a connection.  Return an object of type @class{connection}.

@example
(import (rnrs)
  (compensations)
  (prefix (foreign databases postgresql) pg:))

(with-compensations
  (letrec
      ((conn (compensate
                 (pg:connect-db "dbname=nausicaa-test")
               (with
                (pg:finish conn)))))
    (if (enum-set=? (pg:connection-status ok)
                    (pg:status conn))
         ---)))
@end example
@end defun


@defun finish @var{conn}
@findex @func{PQfinish}
Wrapper for @func{PQfinish}.  Finalise the database connection
referenced by @var{conn}.
@end defun


@defun reset @var{conn}
@findex @func{PQreset}
Wrapper for @func{PQreset}.  Reset the database connection referenced by
@var{conn}: close the connection and try to open it again with the same
parameters.
@end defun


@defun set-db-login @var{pghost} @var{pgport} @var{pgoptions} @var{pgtty} @var{dbname} @var{login} @var{pwd}
@findex @func{PQsetdbLogin}
Wrapper for @func{PQsetdbLogin}.  Connect to a database according to the
given arguments, which must be Scheme strings @var{connect-info} or
@false{} when the default value is desired; this function is deprecated
in favor of the above ones.  Return an object of type
@class{connection}.
@end defun


@defun set-db @var{pghost} @var{pgport} @var{pgoptions} @var{pgtty} @var{dbname}
@findex @func{PQsetdb}
Call @func{set-db-login} with @var{login} and @var{pwd} set to @false{}.
@end defun

@c page
@node connect async
@section Connecting asynchronously


In the following descriptions, the @var{conn} argument is always a
Scheme object of type @class{connection}.


@defun connect-start
@defunx connect-start @var{connect-info}
@findex @func{PQconnectStart}
Wrapper for @func{PQconnectStart}.  Begin connecting to a database
without blocking; the argument is the same as the one to
@func{connect-db}.
@end defun


@defun connect-poll @var{conn}
@findex @func{PQconnectPoll}
Wrapper for @func{PQconnectPoll}.  Query the connection object
@var{conn} for the next action to perform in a non--blocking connection
operation; return an enumeration set of type @code{enum-polling-status}.

@smallexample
(import (nausicaa)
  (compensations)
  (foreign memory)
  (records)
  (prefix (foreign databases postgresql) pg:)
  (prefix (posix sizeof) posix:)
  (prefix (posix fd) posix:)
  (for (prefix (posix typedefs) posix:) expand run)
  (for (prefix (posix extensions) posix:) expand))

(with-compensations
  (letrec ((conn (compensate
                     (pg:connect-start "dbname=nausicaa-test")
                   (with
                    (pg:finish conn)))))
    (let ((fd       (pg:socket conn))
          (rd-fdset (posix:make-fdset malloc-block/c))
          (wr-fdset (posix:make-fdset malloc-block/c))
          (ex-fdset (posix:make-fdset malloc-block/c))
          (timeout  (posix:make-struct-timeval malloc-block/c)))

      (define (%poll set)
        (let loop ()
          (posix:FD_ZERO rd-fdset)
          (posix:FD_ZERO wr-fdset)
          (posix:FD_ZERO ex-fdset)
          (posix:FD_SET fd set)
          (posix:select posix:FD_SETSIZE
                        rd-fdset wr-fdset ex-fdset timeout)
          (unless (posix:FD_ISSET fd set)
            (loop))))

      (with-fields* (((sec usec) posix:struct-timeval* timeout))
        (set! timeout.sec  2)
        (set! timeout.usec 0))

      (let loop ((status (pg:polling-status writing)))
        (cond ((enum-set=? status (pg:polling-status ok))
               #t)
              ((enum-set=? status (pg:polling-status reading))
               (%poll rd-fdset)
               (loop (pg:connect-poll conn)))
              ((enum-set=? status (pg:polling-status writing))
               (%poll wr-fdset)
               (loop (pg:connect-poll conn)))
              (else
               (error ---)))))
      ---))
@end smallexample
@end defun


@defun reset-start @var{conn}
@findex @func{PQresetStart}
Wrapper for @func{PQresetStart}.  Start an asynchronous reset of the
connection referenced by @var{conn}; return @true{} if the operation
succeeds and we can go on by calling @func{reset-poll}.
@end defun


@defun reset-poll @var{conn}
@findex @func{PQresetPoll}
Wrapper for @func{PQresetPoll}.  Query the connection object @var{conn}
for the next action to perform in a non--blocking reset operation;
return an enumeration set of type @code{enum-polling-status}.

Usage of this function if equal to the usage of @func{connect-poll}.
@end defun

@c page
@node connect misc
@section Other connect--related functions


@defun connection-defaults
@findex @func{PQconndefaults}
Wrapper for @func{PQconndefaults}.  Return a list of records of type
@class{connect-option} representing the default connection options.
@end defun


@defun connection-info-parse @var{connect-info}
@findex @func{PQconninfoParse}
Wrapper for @func{PQconninfoParse}.  Parse the Scheme string
@var{connect-info} as a list of connection options; return a list of
records of type @class{connect-option}.  If the string is invalid, raise
an exception.
@end defun

@c page
@node inspect
@chapter Inspection


The following bindings are exported by the @library{foreign databases
postgresql primitives} library and reexported by the @library{foreign
databases postgresql} library.  It is suggested to import these
libraries by prefixing the bindings, for example with @code{pg:}.


@defun status @var{conn}
Wrapper for @func{PQstatus}.  Return an enumeration set of type
@code{enum-connection-status} describing the current state of the
@class{connection} object @var{conn}.
@end defun


@defun status/ok? @var{conn}
@defunx status/bad? @var{conn}
@defunx status/started? @var{conn}
@defunx status/made? @var{conn}
@defunx status/awaiting-response? @var{conn}
@defunx status/auth-ok? @var{conn}
@defunx status/setenv? @var{conn}
@defunx status/ssl-startup? @var{conn}
@defunx status/needed? @var{conn}
Return @true{} if the state of the @class{connection} object @var{conn}
is the name one.
@end defun


@defun socket @var{conn}
@findex @func{PQsocket}
Wrapper for @func{PQsocket}.  Return a @class{fd} object representing
the socket used by the @class{connection} object @var{conn}.
@end defun






@c page
@node primitives
@chapter Miscellaneous primitive bindings


The following bindings are exported by the @library{foreign databases
postgresql primitives} library and reexported by the @library{foreign
databases postgresql} library.  The functions are reexported ``as is''
from the @library{foreign databases postgresql platform} library.  It is
suggested to import these libraries by prefixing the bindings, for
example with @code{pg:}.


@defun conninfo-free
@findex @func{PQconninfoFree}
Alias for @func{PQconninfoFree}.
@end defun


@defun get-cancel
@findex @func{PQgetCancel}
Alias for @func{PQgetCancel}.
@end defun


@defun free-cancel
@findex @func{PQfreeCancel}
Alias for @func{PQfreeCancel}.
@end defun


@defun cancel
@findex @func{PQcancel}
Alias for @func{PQcancel}.
@end defun


@defun request-cancel
@findex @func{PQrequestCancel}
Alias for @func{PQrequestCancel}.
@end defun


@defun db
@findex @func{PQdb}
Alias for @func{PQdb}.
@end defun


@defun user
@findex @func{PQuser}
Alias for @func{PQuser}.
@end defun


@defun pass
@findex @func{PQpass}
Alias for @func{PQpass}.
@end defun


@defun host
@findex @func{PQhost}
Alias for @func{PQhost}.
@end defun


@defun port
@findex @func{PQport}
Alias for @func{PQport}.
@end defun


@defun tty
@findex @func{PQtty}
Alias for @func{PQtty}.
@end defun


@defun options
@findex @func{PQoptions}
Alias for @func{PQoptions}.
@end defun


@defun status
@findex @func{PQstatus}
Alias for @func{PQstatus}.
@end defun


@defun transaction-status
@findex @func{PQtransactionStatus}
Alias for @func{PQtransactionStatus}.
@end defun


@defun parameter-status
@findex @func{PQparameterStatus}
Alias for @func{PQparameterStatus}.
@end defun


@defun protocol-version
@findex @func{PQprotocolVersion}
Alias for @func{PQprotocolVersion}.
@end defun


@defun server-version
@findex @func{PQserverVersion}
Alias for @func{PQserverVersion}.
@end defun


@defun error-message
@findex @func{PQerrorMessage}
Alias for @func{PQerrorMessage}.
@end defun


@defun backend-pid
@findex @func{PQbackendPID}
Alias for @func{PQbackendPID}.
@end defun


@defun connection-needs-password
@findex @func{PQconnectionNeedsPassword}
Alias for @func{PQconnectionNeedsPassword}.
@end defun


@defun connection-used-password
@findex @func{PQconnectionUsedPassword}
Alias for @func{PQconnectionUsedPassword}.
@end defun


@defun client-encoding
@findex @func{PQclientEncoding}
Alias for @func{PQclientEncoding}.
@end defun


@defun set-client-encoding
@findex @func{PQsetClientEncoding}
Alias for @func{PQsetClientEncoding}.
@end defun


@defun getssl
@findex @func{PQgetssl}
Alias for @func{PQgetssl}.
@end defun


@defun init-ssl
@findex @func{PQinitSSL}
Alias for @func{PQinitSSL}.
@end defun


@defun init-open-ssl
@findex @func{PQinitOpenSSL}
Alias for @func{PQinitOpenSSL}.
@end defun


@defun set-error-verbosity
@findex @func{PQsetErrorVerbosity}
Alias for @func{PQsetErrorVerbosity}.
@end defun


@defun trace
@findex @func{PQtrace}
Alias for @func{PQtrace}.
@end defun


@defun untrace
@findex @func{PQuntrace}
Alias for @func{PQuntrace}.
@end defun


@defun set-notice-receiver
@findex @func{PQsetNoticeReceiver}
Alias for @func{PQsetNoticeReceiver}.
@end defun


@defun set-notice-processor
@findex @func{PQsetNoticeProcessor}
Alias for @func{PQsetNoticeProcessor}.
@end defun


@defun register-thread-lock
@findex @func{PQregisterThreadLock}
Alias for @func{PQregisterThreadLock}.
@end defun


@defun exec
@findex @func{PQexec}
Alias for @func{PQexec}.
@end defun


@defun exec-params
@findex @func{PQexecParams}
Alias for @func{PQexecParams}.
@end defun


@defun prepare
@findex @func{PQprepare}
Alias for @func{PQprepare}.
@end defun


@defun exec-prepared
@findex @func{PQexecPrepared}
Alias for @func{PQexecPrepared}.
@end defun


@defun send-query
@findex @func{PQsendQuery}
Alias for @func{PQsendQuery}.
@end defun


@defun send-query-params
@findex @func{PQsendQueryParams}
Alias for @func{PQsendQueryParams}.
@end defun


@defun send-prepare
@findex @func{PQsendPrepare}
Alias for @func{PQsendPrepare}.
@end defun


@defun send-query-prepared
@findex @func{PQsendQueryPrepared}
Alias for @func{PQsendQueryPrepared}.
@end defun


@defun get-result
@findex @func{PQgetResult}
Alias for @func{PQgetResult}.
@end defun


@defun is-busy
@findex @func{PQisBusy}
Alias for @func{PQisBusy}.
@end defun


@defun consume-input
@findex @func{PQconsumeInput}
Alias for @func{PQconsumeInput}.
@end defun


@defun notifies
@findex @func{PQnotifies}
Alias for @func{PQnotifies}.
@end defun


@defun put-copy-data
@findex @func{PQputCopyData}
Alias for @func{PQputCopyData}.
@end defun


@defun put-copy-end
@findex @func{PQputCopyEnd}
Alias for @func{PQputCopyEnd}.
@end defun


@defun get-copy-data
@findex @func{PQgetCopyData}
Alias for @func{PQgetCopyData}.
@end defun


@defun getline
@findex @func{PQgetline}
Alias for @func{PQgetline}.
@end defun


@defun putline
@findex @func{PQputline}
Alias for @func{PQputline}.
@end defun


@defun getline-async
@findex @func{PQgetlineAsync}
Alias for @func{PQgetlineAsync}.
@end defun


@defun putnbytes
@findex @func{PQputnbytes}
Alias for @func{PQputnbytes}.
@end defun


@defun endcopy
@findex @func{PQendcopy}
Alias for @func{PQendcopy}.
@end defun


@defun setnonblocking
@findex @func{PQsetnonblocking}
Alias for @func{PQsetnonblocking}.
@end defun


@defun isnonblocking
@findex @func{PQisnonblocking}
Alias for @func{PQisnonblocking}.
@end defun


@defun isthreadsafe
@findex @func{PQisthreadsafe}
Alias for @func{PQisthreadsafe}.
@end defun


@defun flush
@findex @func{PQflush}
Alias for @func{PQflush}.
@end defun


@defun fn
@findex @func{PQfn}
Alias for @func{PQfn}.
@end defun


@defun result-status
@findex @func{PQresultStatus}
Alias for @func{PQresultStatus}.
@end defun


@defun res-status
@findex @func{PQresStatus}
Alias for @func{PQresStatus}.
@end defun


@defun result-error-message
@findex @func{PQresultErrorMessage}
Alias for @func{PQresultErrorMessage}.
@end defun


@defun result-error-field
@findex @func{PQresultErrorField}
Alias for @func{PQresultErrorField}.
@end defun


@defun ntuples
@findex @func{PQntuples}
Alias for @func{PQntuples}.
@end defun


@defun nfields
@findex @func{PQnfields}
Alias for @func{PQnfields}.
@end defun


@defun binary-tuples
@findex @func{PQbinaryTuples}
Alias for @func{PQbinaryTuples}.
@end defun


@defun fname
@findex @func{PQfname}
Alias for @func{PQfname}.
@end defun


@defun fnumber
@findex @func{PQfnumber}
Alias for @func{PQfnumber}.
@end defun


@defun ftable
@findex @func{PQftable}
Alias for @func{PQftable}.
@end defun


@defun ftablecol
@findex @func{PQftablecol}
Alias for @func{PQftablecol}.
@end defun


@defun fformat
@findex @func{PQfformat}
Alias for @func{PQfformat}.
@end defun


@defun ftype
@findex @func{PQftype}
Alias for @func{PQftype}.
@end defun


@defun fsize
@findex @func{PQfsize}
Alias for @func{PQfsize}.
@end defun


@defun fmod
@findex @func{PQfmod}
Alias for @func{PQfmod}.
@end defun


@defun cmd-status
@findex @func{PQcmdStatus}
Alias for @func{PQcmdStatus}.
@end defun


@defun oid-status
@findex @func{PQoidStatus}
Alias for @func{PQoidStatus}.
@end defun


@defun oid-value
@findex @func{PQoidValue}
Alias for @func{PQoidValue}.
@end defun


@defun cmd-tuples
@findex @func{PQcmdTuples}
Alias for @func{PQcmdTuples}.
@end defun


@defun getvalue
@findex @func{PQgetvalue}
Alias for @func{PQgetvalue}.
@end defun


@defun getlength
@findex @func{PQgetlength}
Alias for @func{PQgetlength}.
@end defun


@defun getisnull
@findex @func{PQgetisnull}
Alias for @func{PQgetisnull}.
@end defun


@defun nparams
@findex @func{PQnparams}
Alias for @func{PQnparams}.
@end defun


@defun paramtype
@findex @func{PQparamtype}
Alias for @func{PQparamtype}.
@end defun


@defun describe-prepared
@findex @func{PQdescribePrepared}
Alias for @func{PQdescribePrepared}.
@end defun


@defun describe-portal
@findex @func{PQdescribePortal}
Alias for @func{PQdescribePortal}.
@end defun


@defun send-describe-prepared
@findex @func{PQsendDescribePrepared}
Alias for @func{PQsendDescribePrepared}.
@end defun


@defun send-describe-portal
@findex @func{PQsendDescribePortal}
Alias for @func{PQsendDescribePortal}.
@end defun


@defun clear
@findex @func{PQclear}
Alias for @func{PQclear}.
@end defun


@defun freemem
@findex @func{PQfreemem}
Alias for @func{PQfreemem}.
@end defun


@defun make-empty-pg-result
@findex @func{PQmakeEmptyPGresult}
Alias for @func{PQmakeEmptyPGresult}.
@end defun


@defun copy-result
@findex @func{PQcopyResult}
Alias for @func{PQcopyResult}.
@end defun


@defun set-result-attrs
@findex @func{PQsetResultAttrs}
Alias for @func{PQsetResultAttrs}.
@end defun


@defun result-alloc
@findex @func{PQresultAlloc}
Alias for @func{PQresultAlloc}.
@end defun


@defun setvalue
@findex @func{PQsetvalue}
Alias for @func{PQsetvalue}.
@end defun


@defun escape-string-conn
@findex @func{PQescapeStringConn}
Alias for @func{PQescapeStringConn}.
@end defun


@defun escape-bytea-conn
@findex @func{PQescapeByteaConn}
Alias for @func{PQescapeByteaConn}.
@end defun


@defun unescape-bytea
@findex @func{PQunescapeBytea}
Alias for @func{PQunescapeBytea}.
@end defun


@defun escape-string
@findex @func{PQescapeString}
Alias for @func{PQescapeString}.
@end defun


@defun escape-bytea
@findex @func{PQescapeBytea}
Alias for @func{PQescapeBytea}.
@end defun


@defun print
@findex @func{PQprint}
Alias for @func{PQprint}.
@end defun


@defun display-tuples
@findex @func{PQdisplayTuples}
Alias for @func{PQdisplayTuples}.
@end defun


@defun print-tuples
@findex @func{PQprintTuples}
Alias for @func{PQprintTuples}.
@end defun


@defun lo-open
@findex @func{lo_open}
Alias for @func{lo_open}.
@end defun


@defun lo-close
@findex @func{lo_close}
Alias for @func{lo_close}.
@end defun


@defun lo-read
@findex @func{lo_read}
Alias for @func{lo_read}.
@end defun


@defun lo-write
@findex @func{lo_write}
Alias for @func{lo_write}.
@end defun


@defun lo-lseek
@findex @func{lo_lseek}
Alias for @func{lo_lseek}.
@end defun


@defun lo-creat
@findex @func{lo_creat}
Alias for @func{lo_creat}.
@end defun


@defun lo-create
@findex @func{lo_create}
Alias for @func{lo_create}.
@end defun


@defun lo-tell
@findex @func{lo_tell}
Alias for @func{lo_tell}.
@end defun


@defun lo-truncate
@findex @func{lo_truncate}
Alias for @func{lo_truncate}.
@end defun


@defun lo-unlink
@findex @func{lo_unlink}
Alias for @func{lo_unlink}.
@end defun


@defun lo-import
@findex @func{lo_import}
Alias for @func{lo_import}.
@end defun


@defun lo-import-with-oid
@findex @func{lo_import_with_oid}
Alias for @func{lo_import_with_oid}.
@end defun


@defun lo-export
@findex @func{lo_export}
Alias for @func{lo_export}.
@end defun


@defun mblen
@findex @func{PQmblen}
Alias for @func{PQmblen}.
@end defun


@defun dsplen
@findex @func{PQdsplen}
Alias for @func{PQdsplen}.
@end defun


@defun env2encoding
@findex @func{PQenv2encoding}
Alias for @func{PQenv2encoding}.
@end defun


@defun encrypt-password
@findex @func{PQencryptPassword}
Alias for @func{PQencryptPassword}.
@end defun


@defun char-to-encoding
@findex @func{pg_char_to_encoding}
Alias for @func{pg_char_to_encoding}.
@end defun


@defun encoding-to-char
@findex @func{pg_encoding_to_char}
Alias for @func{pg_encoding_to_char}.
@end defun


@defun valid-server-encoding-id
@findex @func{pg_valid_server_encoding_id
Alias for @func{pg_valid_server_encoding_id}
@end defun


@defun free-notify
@findex @func{PQfreeNotify}
Alias for @func{PQfreeNotify}.
@end defun


@defvr Constant invalid-oid
@vindex @func{InvalidOid}
Alias for @func{InvalidOid}.
@end defvr


@defvr Constant no-password-supplied
@vindex @func{PQnoPasswordSupplied}
Alias for @func{PQnoPasswordSupplied}.
@end defvr

@c page
@node compensations
@chapter Compensated constructors


The following bindings are exported by the @library{foreign databases
postgresql compensated} library.  This @api{} makes use of the
@library{compensations} library, @nauref{compensations, Compensation
stacks}.


@defun connect-db/c @var{connect-info}
Wrapper for @func{connect-db} which pushes, on the current compensation
stack, the appropriate call to @func{finish} to close the database
connection.
@end defun

@c page

@include gpl-3.0.texiinc
@include fdl-1.3.texiinc

@c page
@node references
@appendix Bibliography and references



@c page
@node concept index
@appendix An entry for each concept

@printindex cp

@node function index
@appendix An entry for each function.

@printindex fn

@node variable index
@appendix An entry for each variable.

@printindex vr

@node type index
@appendix An entry for each type.

@printindex tp

@contents
@bye

@c end of file
