(library (nausicaa r6rs identifier-lexer-table)
  (export
    r6rs-identifier-lexer-table)
  (import (rnrs) (nausicaa silex lexer)(nausicaa silex default-error-handler)(nausicaa parser-tools lexical-token)(nausicaa parser-tools source-location))

;
; Table generated from the file identifier-lexer-table.l by SILex 1.0
;

(define r6rs-identifier-lexer-table
  (vector
   'all
   (lambda (yycontinue yygetc yyungetc)
     (lambda (yytext yyline yycolumn yyoffset)
       			(silex-default-eof-handler)
       ))
   (lambda (yycontinue yygetc yyungetc)
     (lambda (yytext yyline yycolumn yyoffset)
         		(silex-default-error-handler)

;;; end of file
       ))
   (vector
    #t
    (lambda (yycontinue yygetc yyungetc)
      (lambda (yytext yyline yycolumn yyoffset)
            		(string->symbol yytext)
        ))
    #t
    (lambda (yycontinue yygetc yyungetc)
      (lambda (yytext yyline yycolumn yyoffset)
                     	(string->symbol yytext)
        ))
    #t
    (lambda (yycontinue yygetc yyungetc)
      (lambda (yytext yyline yycolumn yyoffset)
                  	(silex-default-error-handler yytext)
        ))
    #t
    (lambda (yycontinue yygetc yyungetc)
      (lambda (yytext yyline yycolumn yyoffset)
                           	(silex-default-error-handler yytext)
        )))
   'code
   (lambda (<<EOF>>-pre-action
            <<ERROR>>-pre-action
            rules-pre-action
            IS)
     (letrec
         ((user-action-<<EOF>> #f)
          (user-action-<<ERROR>> #f)
          (user-action-0 #f)
          (user-action-1 #f)
          (user-action-2 #f)
          (user-action-3 #f)
          (start-go-to-end    (:input-system-start-go-to-end	IS))
          (end-go-to-point    (:input-system-end-go-to-point	IS))
          (init-lexeme        (:input-system-init-lexeme	IS))
          (get-start-line     (:input-system-get-start-line	IS))
          (get-start-column   (:input-system-get-start-column	IS))
          (get-start-offset   (:input-system-get-start-offset	IS))
          (peek-left-context  (:input-system-peek-left-context	IS))
          (peek-char          (:input-system-peek-char		IS))
          (read-char          (:input-system-read-char		IS))
          (get-start-end-text (:input-system-get-start-end-text IS))
          (user-getc          (:input-system-user-getc		IS))
          (user-ungetc        (:input-system-user-ungetc	IS))
          (action-<<EOF>>
           (lambda (yyline yycolumn yyoffset)
             (user-action-<<EOF>> "" yyline yycolumn yyoffset)))
          (action-<<ERROR>>
           (lambda (yyline yycolumn yyoffset)
             (user-action-<<ERROR>> "" yyline yycolumn yyoffset)))
          (action-0
           (lambda (yyline yycolumn yyoffset)
             (let ((yytext (get-start-end-text)))
               (start-go-to-end)
               (user-action-0 yytext yyline yycolumn yyoffset))))
          (action-1
           (lambda (yyline yycolumn yyoffset)
             (let ((yytext (get-start-end-text)))
               (start-go-to-end)
               (user-action-1 yytext yyline yycolumn yyoffset))))
          (action-2
           (lambda (yyline yycolumn yyoffset)
             (let ((yytext (get-start-end-text)))
               (start-go-to-end)
               (user-action-2 yytext yyline yycolumn yyoffset))))
          (action-3
           (lambda (yyline yycolumn yyoffset)
             (let ((yytext (get-start-end-text)))
               (start-go-to-end)
               (user-action-3 yytext yyline yycolumn yyoffset))))
          (state-0
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (< c 60)
                       (if (< c 44)
                           (if (< c 36)
                               (if (= c 33)
                                   (state-5 action)
                                   action)
                               (if (< c 42)
                                   (if (< c 39)
                                       (state-5 action)
                                       action)
                                   (if (< c 43)
                                       (state-5 action)
                                       (state-3 action))))
                           (if (< c 47)
                               (if (< c 45)
                                   action
                                   (if (< c 46)
                                       (state-1 action)
                                       (state-2 action)))
                               (if (< c 58)
                                   (if (< c 48)
                                       (state-5 action)
                                       action)
                                   (if (< c 59)
                                       (state-5 action)
                                       action))))
                       (if (< c 96)
                           (if (< c 91)
                               (if (= c 64)
                                   action
                                   (state-5 action))
                               (if (< c 93)
                                   (if (< c 92)
                                       action
                                       (state-4 action))
                                   (if (< c 94)
                                       action
                                       (state-5 action))))
                           (if (< c 126)
                               (if (< c 97)
                                   action
                                   (if (< c 123)
                                       (state-5 action)
                                       action))
                               (if (< c 57344)
                                   (if (< c 55296)
                                       (state-5 action)
                                       action)
                                   (if (< c 1114112)
                                       (state-5 action)
                                       action)))))
                   action))))
          (state-1
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (= c 62)
                       (state-6 action-1)
                       action-1)
                   action-1))))
          (state-2
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (= c 46)
                       (state-7 action)
                       action)
                   action))))
          (state-3
           (lambda (action)
             (end-go-to-point)
             action-1))
          (state-4
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (= c 120)
                       (state-8 action)
                       action)
                   action))))
          (state-5
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 74)
                       (if (< c 45)
                           (if (< c 39)
                               (if (< c 34)
                                   (if (< c 33)
                                       (state-9 action-0)
                                       (state-11 action-0))
                                   (if (< c 35)
                                       (state-9 action-0)
                                       (if (< c 36)
                                           action-0
                                           (state-11 action-0))))
                               (if (< c 41)
                                   (if (< c 40)
                                       (state-9 action-0)
                                       action-0)
                                   (if (< c 42)
                                       (state-9 action-0)
                                       (if (< c 44)
                                           (state-11 action-0)
                                           (state-9 action-0)))))
                           (if (< c 67)
                               (if (< c 60)
                                   (if (< c 59)
                                       (state-11 action-0)
                                       action-0)
                                   (if (= c 65)
                                       (state-5 action-0)
                                       (state-11 action-0)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-5 action-0)
                                       (state-11 action-0))
                                   (if (< c 70)
                                       (state-5 action-0)
                                       (if (< c 72)
                                           (state-11 action-0)
                                           (state-5 action-0))))))
                       (if (< c 94)
                           (if (< c 87)
                               (if (< c 81)
                                   (if (< c 80)
                                       (state-11 action-0)
                                       (state-5 action-0))
                                   (if (< c 83)
                                       (state-11 action-0)
                                       (if (< c 85)
                                           (state-5 action-0)
                                           (state-11 action-0))))
                               (if (< c 91)
                                   (if (< c 88)
                                       (state-5 action-0)
                                       (state-11 action-0))
                                   (if (= c 92)
                                       (state-10 action-0)
                                       (state-9 action-0))))
                           (if (< c 125)
                               (if (< c 97)
                                   (if (< c 96)
                                       (state-11 action-0)
                                       (state-9 action-0))
                                   (if (< c 123)
                                       (state-11 action-0)
                                       (if (< c 124)
                                           action-0
                                           (state-9 action-0))))
                               (if (< c 55296)
                                   (if (< c 126)
                                       action-0
                                       (state-11 action-0))
                                   (if (< c 57344)
                                       (state-9 action-0)
                                       (if (< c 1114112)
                                           (state-11 action-0)
                                           (state-9 action-0)))))))
                   action-0))))
          (state-6
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 74)
                       (if (< c 45)
                           (if (< c 39)
                               (if (< c 34)
                                   (if (< c 33)
                                       (state-12 action-1)
                                       (state-14 action-1))
                                   (if (< c 35)
                                       (state-12 action-1)
                                       (if (< c 36)
                                           action-1
                                           (state-14 action-1))))
                               (if (< c 41)
                                   (if (< c 40)
                                       (state-12 action-1)
                                       action-1)
                                   (if (< c 42)
                                       (state-12 action-1)
                                       (if (< c 44)
                                           (state-14 action-1)
                                           (state-12 action-1)))))
                           (if (< c 67)
                               (if (< c 60)
                                   (if (< c 59)
                                       (state-14 action-1)
                                       action-1)
                                   (if (= c 65)
                                       (state-6 action-1)
                                       (state-14 action-1)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-6 action-1)
                                       (state-14 action-1))
                                   (if (< c 70)
                                       (state-6 action-1)
                                       (if (< c 72)
                                           (state-14 action-1)
                                           (state-6 action-1))))))
                       (if (< c 94)
                           (if (< c 87)
                               (if (< c 81)
                                   (if (< c 80)
                                       (state-14 action-1)
                                       (state-6 action-1))
                                   (if (< c 83)
                                       (state-14 action-1)
                                       (if (< c 85)
                                           (state-6 action-1)
                                           (state-14 action-1))))
                               (if (< c 91)
                                   (if (< c 88)
                                       (state-6 action-1)
                                       (state-14 action-1))
                                   (if (= c 92)
                                       (state-13 action-1)
                                       (state-12 action-1))))
                           (if (< c 125)
                               (if (< c 97)
                                   (if (< c 96)
                                       (state-14 action-1)
                                       (state-12 action-1))
                                   (if (< c 123)
                                       (state-14 action-1)
                                       (if (< c 124)
                                           action-1
                                           (state-12 action-1))))
                               (if (< c 55296)
                                   (if (< c 126)
                                       action-1
                                       (state-14 action-1))
                                   (if (< c 57344)
                                       (state-12 action-1)
                                       (if (< c 1114112)
                                           (state-14 action-1)
                                           (state-12 action-1)))))))
                   action-1))))
          (state-7
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (= c 46)
                       (state-15 action)
                       action)
                   action))))
          (state-8
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (< c 65)
                       (if (< c 48)
                           action
                           (if (< c 58)
                               (state-16 action)
                               action))
                       (if (< c 97)
                           (if (< c 71)
                               (state-16 action)
                               action)
                           (if (< c 103)
                               (state-16 action)
                               action)))
                   action))))
          (state-9
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 70)
                       (if (< c 60)
                           (if (< c 40)
                               (if (= c 35)
                                   action-2
                                   (state-9 action-2))
                               (if (< c 41)
                                   action-2
                                   (if (< c 59)
                                       (state-9 action-2)
                                       action-2)))
                           (if (< c 67)
                               (if (= c 65)
                                   action-2
                                   (state-9 action-2))
                               (if (= c 68)
                                   (state-9 action-2)
                                   action-2)))
                       (if (< c 85)
                           (if (< c 80)
                               (if (< c 72)
                                   (state-9 action-2)
                                   (if (< c 74)
                                       action-2
                                       (state-9 action-2)))
                               (if (< c 81)
                                   action-2
                                   (if (< c 83)
                                       (state-9 action-2)
                                       action-2)))
                           (if (< c 123)
                               (if (= c 87)
                                   action-2
                                   (state-9 action-2))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 126)
                                       action-2
                                       (state-9 action-2))))))
                   action-2))))
          (state-10
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 72)
                       (if (< c 60)
                           (if (< c 40)
                               (if (= c 35)
                                   action-2
                                   (state-9 action-2))
                               (if (< c 41)
                                   action-2
                                   (if (< c 59)
                                       (state-9 action-2)
                                       action-2)))
                           (if (< c 67)
                               (if (= c 65)
                                   action-2
                                   (state-9 action-2))
                               (if (< c 69)
                                   (if (< c 68)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 70)
                                       action-2
                                       (state-9 action-2)))))
                       (if (< c 88)
                           (if (< c 81)
                               (if (< c 74)
                                   action-2
                                   (if (< c 80)
                                       (state-9 action-2)
                                       action-2))
                               (if (< c 85)
                                   (if (< c 83)
                                       (state-9 action-2)
                                       action-2)
                                   (if (< c 87)
                                       (state-9 action-2)
                                       action-2)))
                           (if (< c 123)
                               (if (= c 120)
                                   (state-17 action-2)
                                   (state-9 action-2))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 126)
                                       action-2
                                       (state-9 action-2))))))
                   action-2))))
          (state-11
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 74)
                       (if (< c 45)
                           (if (< c 39)
                               (if (< c 34)
                                   (if (< c 33)
                                       (state-9 action-0)
                                       (state-11 action-0))
                                   (if (< c 35)
                                       (state-9 action-0)
                                       (if (< c 36)
                                           action-0
                                           (state-11 action-0))))
                               (if (< c 41)
                                   (if (< c 40)
                                       (state-9 action-0)
                                       action-0)
                                   (if (< c 42)
                                       (state-9 action-0)
                                       (if (< c 44)
                                           (state-11 action-0)
                                           (state-9 action-0)))))
                           (if (< c 67)
                               (if (< c 60)
                                   (if (< c 59)
                                       (state-11 action-0)
                                       action-0)
                                   (if (= c 65)
                                       (state-5 action-0)
                                       (state-11 action-0)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-5 action-0)
                                       (state-11 action-0))
                                   (if (< c 70)
                                       (state-5 action-0)
                                       (if (< c 72)
                                           (state-11 action-0)
                                           (state-5 action-0))))))
                       (if (< c 94)
                           (if (< c 87)
                               (if (< c 81)
                                   (if (< c 80)
                                       (state-11 action-0)
                                       (state-5 action-0))
                                   (if (< c 83)
                                       (state-11 action-0)
                                       (if (< c 85)
                                           (state-5 action-0)
                                           (state-11 action-0))))
                               (if (< c 91)
                                   (if (< c 88)
                                       (state-5 action-0)
                                       (state-11 action-0))
                                   (if (= c 92)
                                       (state-10 action-0)
                                       (state-9 action-0))))
                           (if (< c 125)
                               (if (< c 97)
                                   (if (< c 96)
                                       (state-11 action-0)
                                       (state-9 action-0))
                                   (if (< c 123)
                                       (state-11 action-0)
                                       (if (< c 124)
                                           action-0
                                           (state-9 action-0))))
                               (if (< c 55296)
                                   (if (< c 126)
                                       action-0
                                       (state-11 action-0))
                                   (if (< c 57344)
                                       (state-9 action-0)
                                       (if (< c 1114112)
                                           (state-11 action-0)
                                           (state-9 action-0)))))))
                   action-0))))
          (state-12
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 70)
                       (if (< c 60)
                           (if (< c 40)
                               (if (= c 35)
                                   action-3
                                   (state-12 action-3))
                               (if (< c 41)
                                   action-3
                                   (if (< c 59)
                                       (state-12 action-3)
                                       action-3)))
                           (if (< c 67)
                               (if (= c 65)
                                   action-3
                                   (state-12 action-3))
                               (if (= c 68)
                                   (state-12 action-3)
                                   action-3)))
                       (if (< c 85)
                           (if (< c 80)
                               (if (< c 72)
                                   (state-12 action-3)
                                   (if (< c 74)
                                       action-3
                                       (state-12 action-3)))
                               (if (< c 81)
                                   action-3
                                   (if (< c 83)
                                       (state-12 action-3)
                                       action-3)))
                           (if (< c 123)
                               (if (= c 87)
                                   action-3
                                   (state-12 action-3))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 126)
                                       action-3
                                       (state-12 action-3))))))
                   action-3))))
          (state-13
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 72)
                       (if (< c 60)
                           (if (< c 40)
                               (if (= c 35)
                                   action-3
                                   (state-12 action-3))
                               (if (< c 41)
                                   action-3
                                   (if (< c 59)
                                       (state-12 action-3)
                                       action-3)))
                           (if (< c 67)
                               (if (= c 65)
                                   action-3
                                   (state-12 action-3))
                               (if (< c 69)
                                   (if (< c 68)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 70)
                                       action-3
                                       (state-12 action-3)))))
                       (if (< c 88)
                           (if (< c 81)
                               (if (< c 74)
                                   action-3
                                   (if (< c 80)
                                       (state-12 action-3)
                                       action-3))
                               (if (< c 85)
                                   (if (< c 83)
                                       (state-12 action-3)
                                       action-3)
                                   (if (< c 87)
                                       (state-12 action-3)
                                       action-3)))
                           (if (< c 123)
                               (if (= c 120)
                                   (state-18 action-3)
                                   (state-12 action-3))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 126)
                                       action-3
                                       (state-12 action-3))))))
                   action-3))))
          (state-14
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 74)
                       (if (< c 45)
                           (if (< c 39)
                               (if (< c 34)
                                   (if (< c 33)
                                       (state-12 action-1)
                                       (state-14 action-1))
                                   (if (< c 35)
                                       (state-12 action-1)
                                       (if (< c 36)
                                           action-1
                                           (state-14 action-1))))
                               (if (< c 41)
                                   (if (< c 40)
                                       (state-12 action-1)
                                       action-1)
                                   (if (< c 42)
                                       (state-12 action-1)
                                       (if (< c 44)
                                           (state-14 action-1)
                                           (state-12 action-1)))))
                           (if (< c 67)
                               (if (< c 60)
                                   (if (< c 59)
                                       (state-14 action-1)
                                       action-1)
                                   (if (= c 65)
                                       (state-6 action-1)
                                       (state-14 action-1)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-6 action-1)
                                       (state-14 action-1))
                                   (if (< c 70)
                                       (state-6 action-1)
                                       (if (< c 72)
                                           (state-14 action-1)
                                           (state-6 action-1))))))
                       (if (< c 94)
                           (if (< c 87)
                               (if (< c 81)
                                   (if (< c 80)
                                       (state-14 action-1)
                                       (state-6 action-1))
                                   (if (< c 83)
                                       (state-14 action-1)
                                       (if (< c 85)
                                           (state-6 action-1)
                                           (state-14 action-1))))
                               (if (< c 91)
                                   (if (< c 88)
                                       (state-6 action-1)
                                       (state-14 action-1))
                                   (if (= c 92)
                                       (state-13 action-1)
                                       (state-12 action-1))))
                           (if (< c 125)
                               (if (< c 97)
                                   (if (< c 96)
                                       (state-14 action-1)
                                       (state-12 action-1))
                                   (if (< c 123)
                                       (state-14 action-1)
                                       (if (< c 124)
                                           action-1
                                           (state-12 action-1))))
                               (if (< c 55296)
                                   (if (< c 126)
                                       action-1
                                       (state-14 action-1))
                                   (if (< c 57344)
                                       (state-12 action-1)
                                       (if (< c 1114112)
                                           (state-14 action-1)
                                           (state-12 action-1)))))))
                   action-1))))
          (state-15
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 70)
                       (if (< c 60)
                           (if (< c 40)
                               (if (= c 35)
                                   action-1
                                   (state-12 action-1))
                               (if (< c 41)
                                   action-1
                                   (if (< c 59)
                                       (state-12 action-1)
                                       action-1)))
                           (if (< c 67)
                               (if (= c 65)
                                   action-1
                                   (state-12 action-1))
                               (if (= c 68)
                                   (state-12 action-1)
                                   action-1)))
                       (if (< c 85)
                           (if (< c 80)
                               (if (< c 72)
                                   (state-12 action-1)
                                   (if (< c 74)
                                       action-1
                                       (state-12 action-1)))
                               (if (< c 81)
                                   action-1
                                   (if (< c 83)
                                       (state-12 action-1)
                                       action-1)))
                           (if (< c 123)
                               (if (= c 87)
                                   action-1
                                   (state-12 action-1))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-1
                                       (state-12 action-1))
                                   (if (< c 126)
                                       action-1
                                       (state-12 action-1))))))
                   action-1))))
          (state-16
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (< c 60)
                       (if (< c 58)
                           (if (< c 48)
                               action
                               (state-16 action))
                           (if (< c 59)
                               action
                               (state-5 action)))
                       (if (< c 71)
                           (if (< c 65)
                               action
                               (state-16 action))
                           (if (< c 97)
                               action
                               (if (< c 103)
                                   (state-16 action)
                                   action))))
                   action))))
          (state-17
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 71)
                       (if (< c 59)
                           (if (< c 40)
                               (if (= c 35)
                                   action-2
                                   (state-9 action-2))
                               (if (< c 48)
                                   (if (< c 41)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 58)
                                       (state-19 action-2)
                                       (state-9 action-2))))
                           (if (< c 67)
                               (if (< c 65)
                                   (if (< c 60)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 66)
                                       (state-20 action-2)
                                       (state-19 action-2)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-20 action-2)
                                       (state-19 action-2))
                                   (if (< c 70)
                                       (state-20 action-2)
                                       (state-19 action-2)))))
                       (if (< c 87)
                           (if (< c 80)
                               (if (< c 72)
                                   (state-9 action-2)
                                   (if (< c 74)
                                       action-2
                                       (state-9 action-2)))
                               (if (< c 83)
                                   (if (< c 81)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 85)
                                       action-2
                                       (state-9 action-2))))
                           (if (< c 123)
                               (if (< c 97)
                                   (if (< c 88)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 103)
                                       (state-19 action-2)
                                       (state-9 action-2)))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 126)
                                       action-2
                                       (state-9 action-2))))))
                   action-2))))
          (state-18
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 71)
                       (if (< c 59)
                           (if (< c 40)
                               (if (= c 35)
                                   action-3
                                   (state-12 action-3))
                               (if (< c 48)
                                   (if (< c 41)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 58)
                                       (state-21 action-3)
                                       (state-12 action-3))))
                           (if (< c 67)
                               (if (< c 65)
                                   (if (< c 60)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 66)
                                       (state-22 action-3)
                                       (state-21 action-3)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-22 action-3)
                                       (state-21 action-3))
                                   (if (< c 70)
                                       (state-22 action-3)
                                       (state-21 action-3)))))
                       (if (< c 87)
                           (if (< c 80)
                               (if (< c 72)
                                   (state-12 action-3)
                                   (if (< c 74)
                                       action-3
                                       (state-12 action-3)))
                               (if (< c 83)
                                   (if (< c 81)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 85)
                                       action-3
                                       (state-12 action-3))))
                           (if (< c 123)
                               (if (< c 97)
                                   (if (< c 88)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 103)
                                       (state-21 action-3)
                                       (state-12 action-3)))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 126)
                                       action-3
                                       (state-12 action-3))))))
                   action-3))))
          (state-19
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 71)
                       (if (< c 59)
                           (if (< c 40)
                               (if (= c 35)
                                   action-2
                                   (state-9 action-2))
                               (if (< c 48)
                                   (if (< c 41)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 58)
                                       (state-19 action-2)
                                       (state-9 action-2))))
                           (if (< c 67)
                               (if (< c 65)
                                   (if (< c 60)
                                       (state-5 action-2)
                                       (state-9 action-2))
                                   (if (< c 66)
                                       (state-20 action-2)
                                       (state-19 action-2)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-20 action-2)
                                       (state-19 action-2))
                                   (if (< c 70)
                                       (state-20 action-2)
                                       (state-19 action-2)))))
                       (if (< c 87)
                           (if (< c 80)
                               (if (< c 72)
                                   (state-9 action-2)
                                   (if (< c 74)
                                       action-2
                                       (state-9 action-2)))
                               (if (< c 83)
                                   (if (< c 81)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 85)
                                       action-2
                                       (state-9 action-2))))
                           (if (< c 123)
                               (if (< c 97)
                                   (if (< c 88)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 103)
                                       (state-19 action-2)
                                       (state-9 action-2)))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-2
                                       (state-9 action-2))
                                   (if (< c 126)
                                       action-2
                                       (state-9 action-2))))))
                   action-2))))
          (state-20
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (< c 60)
                       (if (< c 58)
                           (if (< c 48)
                               action
                               (state-20 action))
                           (if (< c 59)
                               action
                               (state-5 action)))
                       (if (< c 71)
                           (if (< c 65)
                               action
                               (state-20 action))
                           (if (< c 97)
                               action
                               (if (< c 103)
                                   (state-20 action)
                                   action))))
                   action))))
          (state-21
           (lambda (action)
             (end-go-to-point)
             (let ((c (read-char)))
               (if c
                   (if (< c 71)
                       (if (< c 59)
                           (if (< c 40)
                               (if (= c 35)
                                   action-3
                                   (state-12 action-3))
                               (if (< c 48)
                                   (if (< c 41)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 58)
                                       (state-21 action-3)
                                       (state-12 action-3))))
                           (if (< c 67)
                               (if (< c 65)
                                   (if (< c 60)
                                       (state-6 action-3)
                                       (state-12 action-3))
                                   (if (< c 66)
                                       (state-22 action-3)
                                       (state-21 action-3)))
                               (if (< c 69)
                                   (if (< c 68)
                                       (state-22 action-3)
                                       (state-21 action-3))
                                   (if (< c 70)
                                       (state-22 action-3)
                                       (state-21 action-3)))))
                       (if (< c 87)
                           (if (< c 80)
                               (if (< c 72)
                                   (state-12 action-3)
                                   (if (< c 74)
                                       action-3
                                       (state-12 action-3)))
                               (if (< c 83)
                                   (if (< c 81)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 85)
                                       action-3
                                       (state-12 action-3))))
                           (if (< c 123)
                               (if (< c 97)
                                   (if (< c 88)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 103)
                                       (state-21 action-3)
                                       (state-12 action-3)))
                               (if (< c 125)
                                   (if (< c 124)
                                       action-3
                                       (state-12 action-3))
                                   (if (< c 126)
                                       action-3
                                       (state-12 action-3))))))
                   action-3))))
          (state-22
           (lambda (action)
             (let ((c (read-char)))
               (if c
                   (if (< c 60)
                       (if (< c 58)
                           (if (< c 48)
                               action
                               (state-22 action))
                           (if (< c 59)
                               action
                               (state-6 action)))
                       (if (< c 71)
                           (if (< c 65)
                               action
                               (state-22 action))
                           (if (< c 97)
                               action
                               (if (< c 103)
                                   (state-22 action)
                                   action))))
                   action))))
          (start-automaton
           (lambda ()
             (if (peek-char)
                 (state-0 action-<<ERROR>>)
               action-<<EOF>>)))
          (final-lexer
           (lambda ()
             (init-lexeme)
             (let ((yyline (get-start-line))
                   (yycolumn (get-start-column))
                   (yyoffset (get-start-offset)))
               ((start-automaton) yyline yycolumn yyoffset)))))
       (set! user-action-<<EOF>> (<<EOF>>-pre-action
                                  final-lexer user-getc user-ungetc))
       (set! user-action-<<ERROR>> (<<ERROR>>-pre-action
                                    final-lexer user-getc user-ungetc))
       (set! user-action-0 ((vector-ref rules-pre-action 1)
                            final-lexer user-getc user-ungetc))
       (set! user-action-1 ((vector-ref rules-pre-action 3)
                            final-lexer user-getc user-ungetc))
       (set! user-action-2 ((vector-ref rules-pre-action 5)
                            final-lexer user-getc user-ungetc))
       (set! user-action-3 ((vector-ref rules-pre-action 7)
                            final-lexer user-getc user-ungetc))
       final-lexer))))

) ; end of library

