;;; -*- coding: utf-8-unix -*-
;;;
;;;Part of: Nausicaa/Libxml2
;;;Contents: compound library, high-level API
;;;Date: Thu Dec 10, 2009
;;;
;;;Abstract
;;;
;;;
;;;
;;;Copyright (c) 2009, 2010 Marco Maggi <marco.maggi-ipsu@poste.it>
;;;
;;;This program is free software:  you can redistribute it and/or modify
;;;it under the terms of the  GNU General Public License as published by
;;;the Free Software Foundation, either version 3 of the License, or (at
;;;your option) any later version.
;;;
;;;This program is  distributed in the hope that it  will be useful, but
;;;WITHOUT  ANY   WARRANTY;  without   even  the  implied   warranty  of
;;;MERCHANTABILITY  or FITNESS FOR  A PARTICULAR  PURPOSE.  See  the GNU
;;;General Public License for more details.
;;;
;;;You should  have received  a copy of  the GNU General  Public License
;;;along with this program.  If not, see <http://www.gnu.org/licenses/>.
;;;


(library (xml libxml2)
  (export

    ;; Canonical XML and Exclusive XML Canonicalization
    xml-c14n-doc-save-to
    xml-c14n-doc-dump-memory
    xml-c14n-doc-save
    xml-c14n-execute

    ;; Unicode character range checking
    xml-char-in-range
    xml-is-base-char
    xml-is-blank
    xml-is-char
    xml-is-combining
    xml-is-digit
    xml-is-extender
    xml-is-ideographic
    xml-is-pubid-char

    xml-is-base-char-ch
    xml-is-base-char-q
    xml-is-base-char-group
    xml-is-blank-ch
    xml-is-blank-q
    xml-is-char-ch
    xml-is-char-q
    xml-is-char-group
    xml-is-combining-q
    xml-is-combining-group
    xml-is-digit-ch
    xml-is-digit-q
    xml-is-digit-group
    xml-is-extender-ch
    xml-is-extender-q
    xml-is-extender-group
    xml-is-ideographic-q
    xml-is-ideographic-group
    xml-is-pubid-char-tab
    xml-is-pubid-char-ch
    xml-is-pubid-char-q

    ;; Interfaces to the Catalog handling system
    xml-new-catalog
    xml-load-a-catalog
    xml-load-sgml-super-catalog
    xml-convert-sgml-catalog
    xml-a-catalog-add
    xml-a-catalog-remove
    xml-a-catalog-resolve
    xml-a-catalog-resolve-system
    xml-a-catalog-resolve-public
    xml-a-catalog-resolve-uri
    xml-a-catalog-dump
    xml-free-catalog
    xml-catalog-is-empty
    xml-initialize-catalog
    xml-load-catalog
    xml-load-catalogs
    xml-catalog-cleanup
    xml-catalog-dump
    xml-catalog-resolve
    xml-catalog-resolve-system
    xml-catalog-resolve-public
    xml-catalog-resolve-uri
    xml-catalog-add
    xml-catalog-remove
    xml-parse-catalog-file
    xml-catalog-convert
    xml-catalog-free-local
    xml-catalog-add-local
    xml-catalog-local-resolve
    xml-catalog-local-resolve-uri
    xml-catalog-set-debug
    xml-catalog-set-default-prefer
    xml-catalog-set-defaults
    xml-catalog-get-defaults
    xml-catalog-get-system
    xml-catalog-get-public

    ;; Tree debugging APIs
    xml-debug-dump-string
    xml-debug-dump-attr
    xml-debug-dump-attr-list
    xml-debug-dump-one-node
    xml-debug-dump-node
    xml-debug-dump-node-list
    xml-debug-dump-document-head
    xml-debug-dump-document
    xml-debug-dump-dtd
    xml-debug-dump-entities
    xml-debug-check-document
    xml-ls-one-node
    xml-ls-count-node
    xml-bool-to-text
    xml-shell-print-xpath-error
    xml-shell-print-xpath-result
    xml-shell-list
    xml-shell-base
    xml-shell-dir
    xml-shell-load
    xml-shell-print-node
    xml-shell-cat
    xml-shell-write
    xml-shell-save
    xml-shell-validate
    xml-shell-du
    xml-shell-pwd
    xml-shell

    ;; string dictionary
    xml-dict-create
    xml-dict-create-sub
    xml-dict-reference
    xml-dict-free
    xml-dict-lookup
    xml-dict-exists
    xml-dict-qlookup
    xml-dict-owns
    xml-dict-size
    xml-dict-cleanup

    ;; interface for the encoding conversion functions
    xml-init-char-encoding-handlers
    xml-cleanup-char-encoding-handlers
    xml-register-char-encoding-handler
    xml-get-char-encoding-handler
    xml-find-char-encoding-handler
    xml-new-char-encoding-handler
    xml-add-encoding-alias
    xml-del-encoding-alias
    xml-get-encoding-alias
    xml-cleanup-encoding-aliases
    xml-parse-char-encoding
    xml-get-char-encoding-name
    xml-detect-char-encoding
    xml-char-enc-out-func
    xml-char-enc-in-func
    xml-char-enc-first-line
    xml-char-enc-close-func
    utf8-to-isolat1
    isolat1-to-utf8

    ;; interface for the XML entities handling
    xml-initialize-predefined-entities
    xml-new-entity
    xml-add-doc-entity
    xml-add-dtd-entity
    xml-get-predefined-entity
    xml-get-doc-entity
    xml-get-dtd-entity
    xml-get-parameter-entity
    xml-encode-entities
    xml-encode-entities-reentrant
    xml-encode-special-chars
    xml-create-entities-table
    xml-copy-entities-table
    xml-free-entities-table
    xml-dump-entities-table
    xml-dump-entity-decl
    xml-cleanup-predefined-entities

    ;; interface for all global variables of the library
    xml-init-globals
    xml-cleanup-globals
    xml-parser-input-buffer-create-filename-default
    xml-output-buffer-create-filename-default
    xml-initialize-global-state
    xml-thr-def-set-generic-error-func
    xml-thr-def-set-structured-error-func
    xml-register-node-default
    xml-thr-def-register-node-default
    xml-deregister-node-default
    xml-thr-def-deregister-node-default
    xml-thr-def-output-buffer-create-filename-default
    xml-thr-def-parser-input-buffer-create-filename-default
    xml-malloc
    xml-malloc-atomic
    xml-realloc
    xml-free
    xml-mem-strdup

    ;; chained hash tables
    xml-hash-create
    xml-hash-create-dict
    xml-hash-free
    xml-hash-add-entry
    xml-hash-update-entry
    xml-hash-add-entry2
    xml-hash-update-entry2
    xml-hash-add-entry3
    xml-hash-update-entry3
    xml-hash-remove-entry
    xml-hash-remove-entry2
    xml-hash-remove-entry3
    xml-hash-lookup
    xml-hash-lookup2
    xml-hash-lookup3
    xml-hash-qlookup
    xml-hash-qlookup2
    xml-hash-qlookup3
    xml-hash-copy
    xml-hash-size
    xml-hash-scan
    xml-hash-scan3
    xml-hash-scan-full
    xml-hash-scan-full3

    ;; HTML parser
    html-tag-lookup
    html-entity-lookup
    html-entity-value-lookup
    html-is-auto-closed
    html-auto-close-tag
    html-parse-entity-ref
    html-parse-char-ref
    html-parse-element
    html-new-parser-ctxt
    html-create-memory-parser-ctxt
    html-parse-document
    html-sax-parse-doc
    html-parse-doc
    html-sax-parse-file
    html-parse-file
    utf8-to-html
    html-encode-entities
    html-is-script-attribute
    html-handle-omitted-elem
    html-create-push-parser-ctxt
    html-parse-chunk
    html-free-parser-ctxt
    html-ctxt-reset
    html-ctxt-use-options
    html-read-doc
    html-read-file
    html-read-memory
    html-read-fd
    html-read-io
    html-ctxt-read-doc
    html-ctxt-read-file
    html-ctxt-read-memory
    html-ctxt-read-fd
    html-ctxt-read-io
    html-attr-allowed
    html-element-allowed-here
    html-element-status-here
    html-node-status

    ;; specific APIs to process HTML tree, especially serialization
    html-new-doc
    html-new-doc-no-dtd
    html-get-meta-encoding
    html-set-meta-encoding
    html-doc-dump-memory
    html-doc-dump-memory-format
    html-doc-dump
    html-save-file
    html-node-dump
    html-node-dump-file
    html-node-dump-file-format
    html-save-file-enc
    html-save-file-format
    html-node-dump-format-output
    html-doc-content-dump-output
    html-doc-content-dump-format-output
    html-node-dump-output
    html-is-boolean-attr

    ;; lists interfaces
    xml-list-create
    xml-list-delete
    xml-list-search
    xml-list-reverse-search
    xml-list-insert
    xml-list-append
    xml-list-remove-first
    xml-list-remove-last
    xml-list-remove-all
    xml-list-clear
    xml-list-empty
    xml-list-front
    xml-list-end
    xml-list-size
    xml-list-pop-front
    xml-list-pop-back
    xml-list-push-front
    xml-list-push-back
    xml-list-reverse
    xml-list-sort
    xml-list-walk
    xml-list-reverse-walk
    xml-list-merge
    xml-list-dup
    xml-list-copy
    xml-link-get-data

    ;; minimal FTP implementation
    xml-nano-ftp-init
    xml-nano-ftp-cleanup
    xml-nano-ftp-new-ctxt
    xml-nano-ftp-free-ctxt
    xml-nano-ftp-connect-to
    xml-nano-ftp-open
    xml-nano-ftp-connect
    xml-nano-ftp-close
    xml-nano-ftp-quit
    xml-nano-ftp-scan-proxy
    xml-nano-ftp-proxy
    xml-nano-ftp-update-url
    xml-nano-ftp-get-response
    xml-nano-ftp-check-response
    xml-nano-ftp-cwd
    xml-nano-ftp-dele
    xml-nano-ftp-get-connection
    xml-nano-ftp-close-connection
    xml-nano-ftp-list
    xml-nano-ftp-get-socket
    xml-nano-ftp-get
    xml-nano-ftp-read

    ;; minimal HTTP implementation
    xml-nano-http-init
    xml-nano-http-cleanup
    xml-nano-http-scan-proxy
    xml-nano-http-fetch
    xml-nano-http-method
    xml-nano-http-method-redir
    xml-nano-http-open
    xml-nano-http-open-redir
    xml-nano-http-return-code
    xml-nano-http-auth-header
    xml-nano-http-redir
    xml-nano-http-content-length
    xml-nano-http-encoding
    xml-nano-http-mime-type
    xml-nano-http-read
    xml-nano-http-save
    xml-nano-http-close

    ;; the core parser module
    xml-init-parser
    xml-cleanup-parser
    xml-parser-input-read
    xml-parser-input-grow
    xml-parse-doc
    xml-parse-file
    xml-parse-memory
    xml-substitute-entities-default
    xml-keep-blanks-default
    xml-stop-parser
    xml-pedantic-parser-default
    xml-line-numbers-default
    xml-recover-doc
    xml-recover-memory
    xml-recover-file
    xml-parse-document
    xml-parse-ext-parsed-ent
    xml-sax-user-parse-file
    xml-sax-user-parse-memory
    xml-sax-parse-doc
    xml-sax-parse-memory
    xml-sax-parse-memory-with-data
    xml-sax-parse-file
    xml-sax-parse-file-with-data
    xml-sax-parse-entity
    xml-parse-entity
    xml-sax-parse-dtd
    xml-parse-dtd
    xml-io-parse-dtd
    xml-parse-balanced-chunk-memory
    xml-parse-in-node-context
    xml-parse-balanced-chunk-memory-recover
    xml-parse-external-entity
    xml-parse-ctxt-external-entity
    xml-new-parser-ctxt
    xml-init-parser-ctxt
    xml-clear-parser-ctxt
    xml-free-parser-ctxt
    xml-setup-parser-for-buffer
    xml-create-doc-parser-ctxt
    xml-get-features-list
    xml-get-feature
    xml-set-feature
    xml-create-push-parser-ctxt
    xml-parse-chunk
    xml-create-io-parser-ctxt
    xml-new-io-input-stream
    xml-parser-find-node-info
    xml-init-node-info-seq
    xml-clear-node-info-seq
    xml-parser-find-node-info-index
    xml-parser-add-node-info
    xml-set-external-entity-loader
    xml-get-external-entity-loader
    xml-load-external-entity
    xml-byte-consumed
    xml-ctxt-reset
    xml-ctxt-reset-push
    xml-ctxt-use-options
    xml-read-doc
    xml-read-file
    xml-read-memory
    xml-read-fd
    xml-read-io
    xml-ctxt-read-doc
    xml-ctxt-read-file
    xml-ctxt-read-memory
    xml-ctxt-read-fd
    xml-ctxt-read-io
    xml-has-feature

    ;; pattern expression handling
    xml-free-pattern
    xml-free-pattern-list
    xml-patterncompile
    xml-pattern-match
    xml-pattern-streamable
    xml-pattern-max-depth
    xml-pattern-min-depth
    xml-pattern-from-root
    xml-pattern-get-stream-ctxt
    xml-free-stream-ctxt
    xml-stream-push-node
    xml-stream-push
    xml-stream-push-attr
    xml-stream-pop
    xml-stream-wants-any-node

    ;; implementation of the Relax-NG validation
    xml-relax-ng-init-types
    xml-relax-ng-cleanup-types
    xml-relax-ng-new-parser-ctxt
    xml-relax-ng-new-mem-parser-ctxt
    xml-relax-ng-new-doc-parser-ctxt
    xml-relax-parser-set-flag
    xml-relax-ng-free-parser-ctxt
    xml-relax-ng-set-parser-errors
    xml-relax-ng-get-parser-errors
    xml-relax-ng-set-parser-structured-errors
    xml-relax-ng-parse
    xml-relax-ng-free
    xml-relax-ng-dump
    xml-relax-ng-dump-tree
    xml-relax-ng-set-valid-errors
    xml-relax-ng-get-valid-errors
    xml-relax-ng-set-valid-structured-errors
    xml-relax-ng-new-valid-ctxt
    xml-relax-ng-free-valid-ctxt
    xml-relax-ng-validate-doc
    xml-relax-ng-validate-push-element
    xml-relax-ng-validate-push-cdata
    xml-relax-ng-validate-pop-element
    xml-relax-ng-validate-full-element

    ;; SAX2 parser interface used to build the DOM tree
    xml-sax2-get-public-id
    xml-sax2-get-system-id
    xml-sax2-set-document-locator
    xml-sax2-get-line-number
    xml-sax2-get-column-number
    xml-sax2-is-standalone
    xml-sax2-has-internal-subset
    xml-sax2-has-external-subset
    xml-sax2-internal-subset
    xml-sax2-external-subset
    xml-sax2-get-entity
    xml-sax2-get-parameter-entity
    xml-sax2-resolve-entity
    xml-sax2-entity-decl
    xml-sax2-attribute-decl
    xml-sax2-element-decl
    xml-sax2-notation-decl
    xml-sax2-unparsed-entity-decl
    xml-sax2-start-document
    xml-sax2-end-document
    xml-sax2-start-element
    xml-sax2-end-element
    xml-sax2-start-element-ns
    xml-sax2-end-element-ns
    xml-sax2-reference
    xml-sax2-characters
    xml-sax2-ignorable-whitespace
    xml-sax2-processing-instruction
    xml-sax2-comment
    xml-sax2-cdata-block
    xml-sax-default-version
    xml-sax-version
    xml-sax2-init-default-sax-handler
    xml-sax2-init-html-default-sax-handler
    html-default-sax-handler-init
    xml-sax2-init-docb-default-sax-handler
    docb-default-sax-handler-init
    xml-default-sax-handler-init

    ;; XML Schematron implementation
    xml-schematron-new-parser-ctxt
    xml-schematron-new-mem-parser-ctxt
    xml-schematron-new-doc-parser-ctxt
    xml-schematron-free-parser-ctxt
;;; xmlSchematronSetParserErrors
;;; xmlSchematronGetParserErrors
;;; xmlSchematronIsValid
    xml-schematron-parse
    xml-schematron-free
    xml-schematron-set-valid-structured-errors
;;;    xmlSchematronSetValidErrors
;;;    xmlSchematronGetValidErrors
;;;    xmlSchematronSetValidOptions
;;;    xmlSchematronValidCtxtGetOptions
;;;    xmlSchematronValidateOneElement
    xml-schematron-new-valid-ctxt
    xml-schematron-free-valid-ctxt
    xml-schematron-validate-doc

    ;; interfaces for thread handling
    xml-new-mutex
    xml-mutex-lock
    xml-mutex-unlock
    xml-free-mutex
    xml-new-rmutex
    xml-rmutex-lock
    xml-rmutex-unlock
    xml-free-rmutex
    xml-init-threads
    xml-lock-library
    xml-unlock-library
    xml-get-thread-id
    xml-is-main-thread
    xml-cleanup-threads
    xml-get-global-state
;;;    xmlDllMain

    ;; interfaces for tree manipulation
    xml-validate-ncname
    xml-validate-qname
    xml-validate-name
    xml-validate-nmtoken
    xml-build-qname
    xml-split-qname2
    xml-split-qname3
    xml-set-buffer-allocation-scheme
    xml-get-buffer-allocation-scheme
    xml-buffer-create
    xml-buffer-create-size
    xml-buffer-create-static
    xml-buffer-resize
    xml-buffer-free
    xml-buffer-dump
    xml-buffer-add
    xml-buffer-add-head
    xml-buffer-cat
    xml-buffer-ccat
    xml-buffer-shrink
    xml-buffer-grow
    xml-buffer-empty
    xml-buffer-content
    xml-buffer-set-allocation-scheme
    xml-buffer-length
    xml-create-int-subset
    xml-new-dtd
    xml-get-int-subset
    xml-free-dtd
    xml-new-global-ns
    xml-new-ns
    xml-free-ns
    xml-free-ns-list
    xml-new-doc
    xml-free-doc
    xml-new-doc-prop
    xml-new-prop
    xml-new-ns-prop
    xml-new-ns-prop-eat-name
    xml-free-prop-list
    xml-free-prop
    xml-copy-prop
    xml-copy-prop-list
    xml-copy-dtd
    xml-copy-doc
    xml-new-doc-node
    xml-new-doc-node-eat-name
    xml-new-node
    xml-new-node-eat-name
    xml-new-child
    xml-new-doc-text
    xml-new-text
    xml-new-doc-pi
    xml-new-pi
    xml-new-doc-text-len
    xml-new-text-len
    xml-new-doc-comment
    xml-new-comment
    xml-new-cdata-block
    xml-new-char-ref
    xml-new-reference
    xml-copy-node
    xml-doc-copy-node
    xml-doc-copy-node-list
    xml-copy-node-list
    xml-new-text-child
    xml-new-doc-raw-node
    xml-new-doc-fragment
    xml-get-line-no
    xml-get-node-path
    xml-doc-get-root-element
    xml-get-last-child
    xml-node-is-text
    xml-is-blank-node
    xml-doc-set-root-element
    xml-node-set-name
    xml-add-child
    xml-add-child-list
    xml-replace-node
    xml-add-prev-sibling
    xml-add-sibling
    xml-add-next-sibling
    xml-unlink-node
    xml-text-merge
    xml-text-concat
    xml-free-node-list
    xml-free-node
    xml-set-tree-doc
    xml-set-list-doc
    xml-search-ns
    xml-search-ns-by-href
    xml-get-ns-list
    xml-set-ns
    xml-copy-namespace
    xml-copy-namespace-list
    xml-set-prop
    xml-set-ns-prop
    xml-get-no-ns-prop
    xml-get-prop
    xml-has-prop
    xml-has-ns-prop
    xml-get-ns-prop
    xml-string-get-node-list
    xml-string-len-get-node-list
    xml-node-list-get-string
    xml-node-list-get-raw-string
    xml-node-set-content
    xml-node-set-content-len
    xml-node-add-content
    xml-node-add-content-len
    xml-node-get-content
    xml-node-buf-get-content
    xml-node-get-lang
    xml-node-get-space-preserve
    xml-node-set-lang
    xml-node-set-space-preserve
    xml-node-get-base
    xml-node-set-base
    xml-remove-prop
    xml-unset-ns-prop
    xml-unset-prop
    xml-buffer-write-CHAR
    xml-buffer-write-char
    xml-buffer-write-quoted-string
    xml-doc-ptr
    xml-reconciliate-ns
    xml-doc-dump-format-memory
    xml-doc-dump-memory
    xml-doc-dump-memory-enc
    xml-doc-dump-format-memory-enc
    xml-doc-format-dump
    xml-doc-dump
    xml-elem-dump
    xml-save-file
    xml-save-format-file
    xml-node-dump
    xml-save-file-to
    xml-save-format-file-to
    xml-node-dump-output
    xml-save-format-file-enc
    xml-save-file-enc
    xml-is-xhtml
    xml-get-doc-compress-mode
    xml-set-doc-compress-mode
    xml-get-compress-mode
    xml-set-compress-mode
    xml-dom-wrap-new-ctxt
    xml-dom-wrap-free-ctxt
    xml-dom-wrap-reconcile-namespaces
    xml-dom-wrap-adopt-node
    xml-dom-wrap-remove-node
    xml-dom-wrap-clone-node
    xml-child-element-count
    xml-next-element-sibling
    xml-first-element-child
    xml-last-element-child
    xml-previous-element-sibling

    ;; library of generic URI related routines
    xml-create-uri
    xml-build-uri
    xml-build-relative-uri
    xml-parse-uri
    xml-parse-uri-raw
    xml-parse-uri-reference
    xml-save-uri
    xml-print-uri
    xml-uri-escape-str
    xml-uri-unescape-string
    xml-normalize-uri-path
    xml-uri-escape
    xml-free-uri
    xml-canonic-path
    xml-path-to-uri

    ;; The DTD validation
    xml-add-notation-decl
    xml-copy-notation-table
    xml-free-notation-table
    xml-dump-notation-decl
    xml-dump-notation-table
    xml-new-element-content
    xml-copy-element-content
    xml-free-element-content
    xml-new-doc-element-content
    xml-copy-doc-element-content
    xml-free-doc-element-content
    xml-snprintf-element-content
    xml-sprintf-element-content
    xml-add-element-decl
    xml-copy-element-table
    xml-free-element-table
    xml-dump-element-table
    xml-dump-element-decl
    xml-create-enumeration
    xml-free-enumeration
    xml-copy-enumeration
    xml-add-attribute-decl
    xml-copy-attribute-table
    xml-free-attribute-table
    xml-dump-attribute-table
    xml-dump-attribute-decl
    xml-add-id
    xml-free-id-table
    xml-get-id
    xml-is-id
    xml-remove-id
    xml-add-ref
    xml-free-ref-table
    xml-is-ref
    xml-remove-ref
    xml-get-refs
    xml-new-valid-ctxt
    xml-free-valid-ctxt
    xml-validate-root
    xml-validate-element-decl
    xml-valid-normalize-attribute-value
    xml-valid-ctxt-normalize-attribute-value
    xml-validate-attribute-decl
    xml-validate-attribute-value
    xml-validate-notation-decl
    xml-validate-dtd
    xml-validate-dtd-final
    xml-validate-document
    xml-validate-element
    xml-validate-one-element
    xml-validate-one-attribute
    xml-validate-one-namespace
    xml-validate-document-final
    xml-validate-notation-use
    xml-is-mixed-element
    xml-get-dtd-attr-desc
    xml-get-dtd-qattr-desc
    xml-get-dtd-notation-desc
    xml-get-dtd-qelement-desc
    xml-get-dtd-element-desc
    xml-valid-get-potential-children
    xml-valid-get-valid-elements
    xml-validate-name-value
    xml-validate-names-value
    xml-validate-nmtoken-value
    xml-validate-nmtokens-value
    xml-valid-build-content-model
    xml-validate-push-element
    xml-validate-push-cdata
    xml-validate-pop-element

    ;; implementation of XInclude
    xml-xinclude-process
    xml-xinclude-process-flags
    xml-xinclude-process-flags-data
    xml-xinclude-process-tree-flags-data
    xml-xinclude-process-tree
    xml-xinclude-process-tree-flags
    xml-xinclude-new-context
    xml-xinclude-set-flags
    xml-xinclude-free-context
    xml-xinclude-process-node

    ;; API to build regexp automata
    xml-new-automata
    xml-free-automata
    xml-automata-get-init-state
    xml-automata-set-final-state
    xml-automata-new-state
    xml-automata-new-transition
    xml-automata-new-transition2
    xml-automata-new-neg-trans
    xml-automata-new-count-trans
    xml-automata-new-count-trans2
    xml-automata-new-once-trans
    xml-automata-new-once-trans2
    xml-automata-new-all-trans
    xml-automata-new-epsilon
    xml-automata-new-counted-trans
    xml-automata-new-counter-trans
    xml-automata-new-counter
    xml-automata-compile
    xml-automata-is-determinist

    ;; error handling
    xml-set-generic-error-func
    init-generic-error-default-func
    xml-set-structured-error-func
    xml-parser-print-file-info
    xml-parser-print-file-context
    xml-get-last-error
    xml-reset-last-error
    xml-ctxt-get-last-error
    xml-ctxt-reset-last-error
    xml-reset-error
    xml-copy-error

    ;; interface for the I/O interfaces used by the parser
    xml-cleanup-input-callbacks
    xml-pop-input-callbacks
    xml-register-default-input-callbacks
    xml-alloc-parser-input-buffer
    xml-parser-input-buffer-create-filename
    xml-parser-input-buffer-create-file
    xml-parser-input-buffer-create-fd
    xml-parser-input-buffer-create-mem
    xml-parser-input-buffer-create-static
    xml-parser-input-buffer-create-io
    xml-parser-input-buffer-read
    xml-parser-input-buffer-grow
    xml-parser-input-buffer-push
    xml-free-parser-input-buffer
    xml-parser-get-directory
    xml-register-input-callbacks
    __xml-parser-input-buffer-create-filename
    xml-cleanup-output-callbacks
    xml-register-default-output-callbacks
    xml-alloc-output-buffer
    xml-output-buffer-create-filename
    xml-output-buffer-create-file
    xml-output-buffer-create-buffer
    xml-output-buffer-create-fd
    xml-output-buffer-create-io
    xml-output-buffer-write
    xml-output-buffer-write-string
    xml-output-buffer-write-escape
    xml-output-buffer-flush
    xml-output-buffer-close
    xml-register-output-callbacks
    __xml-output-buffer-create-filename
    xml-register-http-post-callbacks
    xml-check-http-input
    xml-no-net-external-entity-loader
    xml-normalize-windows-path
    xml-check-filename
    xml-file-match
    xml-file-open
    xml-file-read
    xml-file-close
    xml-io-http-match
    xml-io-http-open
    xml-io-http-open-w
    xml-io-http-read
    xml-io-http-close
    xml-io-ftp-match
    xml-io-ftp-open
    xml-io-ftp-read
    xml-io-ftp-close

    ;; interface for the memory allocator
    xml-mem-setup
    xml-mem-get
    xml-gc-mem-setup
    xml-gc-mem-get
    xml-init-memory
    xml-cleanup-memory
    xml-mem-used
    xml-mem-blocks
    xml-mem-display
    xml-mem-display-last
    xml-mem-show
    xml-memory-dump
    xml-mem-malloc
    xml-mem-realloc
    xml-mem-free
    xml-memory-strdup
    xml-malloc-loc
    xml-realloc-loc
    xml-malloc-atomic-loc
    xml-mem-strdup-loc

    ;; dynamic module loading
    xml-module-open
    xml-module-symbol
    xml-module-close
    xml-module-free

    ;; the XMLReader implementation
    xml-new-text-reader
    xml-new-text-reader-filename
    xml-free-text-reader
    xml-text-reader-setup
    xml-text-reader-read
    xml-text-reader-read-inner-xml
    xml-text-reader-read-outer-xml
    xml-text-reader-read-string
    xml-text-reader-read-attribute-value
    xml-text-reader-attribute-count
    xml-text-reader-depth
    xml-text-reader-has-attributes
    xml-text-reader-has-value
    xml-text-reader-is-default
    xml-text-reader-is-empty-element
    xml-text-reader-node-type
    xml-text-reader-quote-char
    xml-text-reader-read-state
    xml-text-reader-is-namespace-decl
    xml-text-reader-const-base-uri
    xml-text-reader-const-local-name
    xml-text-reader-const-name
    xml-text-reader-const-namespace-uri
    xml-text-reader-const-prefix
    xml-text-reader-const-xml-lang
    xml-text-reader-const-string
    xml-text-reader-const-value
    xml-text-reader-base-uri
    xml-text-reader-local-name
    xml-text-reader-name
    xml-text-reader-namespace-uri
    xml-text-reader-prefix
    xml-text-reader-xml-lang
    xml-text-reader-value
    xml-text-reader-close
    xml-text-reader-get-attribute-no
    xml-text-reader-get-attribute
    xml-text-reader-get-attribute-ns
    xml-text-reader-get-remainder
    xml-text-reader-lookup-namespace
    xml-text-reader-move-to-attribute-no
    xml-text-reader-move-to-attribute
    xml-text-reader-move-to-attribute-ns
    xml-text-reader-move-to-first-attribute
    xml-text-reader-move-to-next-attribute
    xml-text-reader-move-to-element
    xml-text-reader-normalization
    xml-text-reader-const-encoding
    xml-text-reader-set-parser-prop
    xml-text-reader-get-parser-prop
    xml-text-reader-current-node
    xml-text-reader-get-parser-line-number
    xml-text-reader-get-parser-column-number
    xml-text-reader-preserve
    xml-text-reader-preserve-pattern
    xml-text-reader-current-doc
    xml-text-reader-expand
    xml-text-reader-next
    xml-text-reader-next-sibling
    xml-text-reader-is-valid
    xml-text-reader-relax-ng-validate
    xml-text-reader-relax-ng-set-schema
    xml-text-reader-schema-validate
    xml-text-reader-schema-validate-ctxt
    xml-text-reader-set-schema
    xml-text-reader-const-xml-version
    xml-text-reader-standalone
    xml-text-reader-byte-consumed
    xml-reader-walker
    xml-reader-for-doc
    xml-reader-for-file
    xml-reader-for-memory
    xml-reader-for-fd
    xml-reader-for-io
    xml-reader-new-walker
    xml-reader-new-doc
    xml-reader-new-file
    xml-reader-new-memory
    xml-reader-new-fd
    xml-reader-new-io
    xml-text-reader-locator-line-number
    xml-text-reader-locator-base-uri
    xml-text-reader-set-error-handler
    xml-text-reader-set-structured-error-handler
    xml-text-reader-get-error-handler

    ;; regular expressions handling
    xml-regexp-compile
    xml-reg-free-regexp
    xml-regexp-exec
    xml-regexp-print
    xml-regexp-is-determinist
    xml-reg-new-exec-ctxt
    xml-reg-free-exec-ctxt
    xml-reg-exec-push-string
    xml-reg-exec-push-string2
    xml-reg-exec-next-values
    xml-reg-exec-err-info
    xml-exp-free-ctxt
    xml-exp-new-ctxt
    xml-exp-ctxt-nb-nodes
    xml-exp-ctxt-nb-cons
    xml-exp-free
    xml-exp-ref
    xml-exp-parse
    xml-exp-new-atom
    xml-exp-new-or
    xml-exp-new-seq
    xml-exp-new-range
    xml-exp-is-nillable
    xml-exp-max-token
    xml-exp-get-language
    xml-exp-get-start
    xml-exp-string-derive
    xml-exp-exp-derive
    xml-exp-subsume
    xml-exp-dump

    ;; the xml document serializer
    xml-save-to-fd
    xml-save-to-filename
    xml-save-to-buffer
    xml-save-to-io
    xml-save-doc
    xml-save-tree
    xml-save-flush
    xml-save-close
    xml-save-set-escape
    xml-save-set-attr-escape

    ;; internal interfaces for XML Schemas
    xml-schema-free-type
    xml-schema-free-wildcard

    ;; incomplete XML Schemas structure implementation
    xml-schema-new-parser-ctxt
    xml-schema-new-mem-parser-ctxt
    xml-schema-new-doc-parser-ctxt
    xml-schema-free-parser-ctxt
    xml-schema-set-parser-errors
    xml-schema-set-parser-structured-errors
    xml-schema-get-parser-errors
    xml-schema-is-valid
    xml-schema-parse
    xml-schema-free
    xml-schema-dump
    xml-schema-set-valid-errors
    xml-schema-set-valid-structured-errors
    xml-schema-get-valid-errors
    xml-schema-set-valid-options
    xml-schema-valid-ctxt-get-options
    xml-schema-new-valid-ctxt
    xml-schema-free-valid-ctxt
    xml-schema-validate-doc
    xml-schema-validate-one-element
    xml-schema-validate-stream
    xml-schema-validate-file
    xml-schema-valid-ctxt-get-parser-ctxt
    xml-schema-sax-plug
    xml-schema-sax-unplug

    ;; implementation of XML Schema Datatypes
    xml-schema-init-types
    xml-schema-cleanup-types
    xml-schema-get-predefined-type
    xml-schema-validate-predefined-type
    xml-schema-val-predef-type-node
    xml-schema-validate-facet
    xml-schema-validate-facet-whtsp
    xml-schema-free-value
    xml-schema-new-facet
    xml-schema-check-facet
    xml-schema-free-facet
    xml-schema-compare-values
    xml-schema-get-built-in-list-simple-type-item-Type
    xml-schema-validate-list-simple-type-facet
    xml-schema-get-built-in-type
    xml-schema-is-built-in-type-facet
    xml-schema-collapse-string
    xml-schema-white-space-replace
    xml-schema-get-facet-value-as-u-long
    xml-schema-validate-length-facet
    xml-schema-validate-length-facet-whtsp
    xml-schema-val-predef-type-node-no-norm
    xml-schema-get-canon-value
    xml-schema-get-canon-value-whtsp
    xml-schema-value-append
    xml-schema-value-get-next
    xml-schema-value-get-as-string
    xml-schema-value-get-as-boolean
    xml-schema-new-string-value
    xml-schema-new-notation-value
    xml-schema-new-qname-value
    xml-schema-compare-values-whtsp
    xml-schema-copy-value
    xml-schema-get-val-type

    ;; set of routines to process strings
    xml-strdup
    xml-strndup
    xml-char-strndup
    xml-char-strdup
    xml-strsub
    xml-strchr
    xml-strstr
    xml-strcasestr
    xml-strcmp
    xml-strncmp
    xml-strcasecmp
    xml-strncasecmp
    xml-str-equal
    xml-str-qequal
    xml-strlen
    xml-strcat
    xml-strncat
    xml-strncat-new
    xml-get-utf8-char
    xml-check-utf8
    xml-utf8-strsize
    xml-utf8-strndup
    xml-utf8-strpos
    xml-utf8-strloc
    xml-utf8-strsub
    xml-utf8-strlen
    xml-utf8-size
    xml-utf8-charcmp

    ;; Unicode character APIs
    xml-ucs-is-aegean-numbers
    xml-ucs-is-alphabetic-presentation-forms
    xml-ucs-is-arabic
    xml-ucs-is-arabic-presentation-forms-a
    xml-ucs-is-arabic-presentation-forms-b
    xml-ucs-is-armenian
    xml-ucs-is-arrows
    xml-ucs-is-basic-latin
    xml-ucs-is-bengali
    xml-ucs-is-block-elements
    xml-ucs-is-bopomofo
    xml-ucs-is-bopomofo-extended
    xml-ucs-is-box-drawing
    xml-ucs-is-braille-patterns
    xml-ucs-is-buhid
    xml-ucs-is-byzantine-musical-symbols
    xml-ucs-is-cjk-compatibility
    xml-ucs-is-cjk-compatibility-forms
    xml-ucs-is-cjk-compatibility-ideographs
    xml-ucs-is-cjk-compatibility-ideographs-supplement
    xml-ucs-is-cjk-radicals-supplement
    xml-ucs-is-cjk-symbolsand-punctuation
    xml-ucs-is-cjk-unified-ideographs
    xml-ucs-is-cjk-unified-ideographs-extension-a
    xml-ucs-is-cjk-unified-ideographs-extension-b
    xml-ucs-is-cherokee
    xml-ucs-is-combining-diacritical-marks
    xml-ucs-is-combining-diacritical-marksfor-symbols
    xml-ucs-is-combining-half-marks
    xml-ucs-is-combining-marksfor-symbols
    xml-ucs-is-control-pictures
    xml-ucs-is-currency-symbols
    xml-ucs-is-cypriot-syllabary
    xml-ucs-is-cyrillic
    xml-ucs-is-cyrillic-supplement
    xml-ucs-is-deseret
    xml-ucs-is-devanagari
    xml-ucs-is-dingbats
    xml-ucs-is-enclosed-alphanumerics
    xml-ucs-is-enclosed-cjk-lettersand-months
    xml-ucs-is-ethiopic
    xml-ucs-is-general-punctuation
    xml-ucs-is-geometric-shapes
    xml-ucs-is-georgian
    xml-ucs-is-gothic
    xml-ucs-is-greek
    xml-ucs-is-greek-extended
    xml-ucs-is-greekand-coptic
    xml-ucs-is-gujarati
    xml-ucs-is-gurmukhi
    xml-ucs-is-halfwidthand-fullwidth-forms
    xml-ucs-is-hangul-compatibility-jamo
    xml-ucs-is-hangul-jamo
    xml-ucs-is-hangul-syllables
    xml-ucs-is-hanunoo
    xml-ucs-is-hebrew
    xml-ucs-is-high-private-use-surrogates
    xml-ucs-is-high-surrogates
    xml-ucs-is-hiragana
    xml-ucs-is-ipa-extensions
    xml-ucs-is-ideographic-description-characters
    xml-ucs-is-kanbun
    xml-ucs-is-kangxi-radicals
    xml-ucs-is-kannada
    xml-ucs-is-katakana
    xml-ucs-is-katakana-phonetic-extensions
    xml-ucs-is-khmer
    xml-ucs-is-khmer-symbols
    xml-ucs-is-lao
    xml-ucs-is-latin1-supplement
    xml-ucs-is-latin-extended-a
    xml-ucs-is-latin-extended-b
    xml-ucs-is-latin-extended-additional
    xml-ucs-is-letterlike-symbols
    xml-ucs-is-limbu
    xml-ucs-is-linear-b-ideograms
    xml-ucs-is-linear-b-syllabary
    xml-ucs-is-low-surrogates
    xml-ucs-is-malayalam
    xml-ucs-is-mathematical-alphanumeric-symbols
    xml-ucs-is-mathematical-operators
    xml-ucs-is-miscellaneous-mathematical-symbols-a
    xml-ucs-is-miscellaneous-mathematical-symbols-b
    xml-ucs-is-miscellaneous-symbols
    xml-ucs-is-miscellaneous-symbolsand-arrows
    xml-ucs-is-miscellaneous-technical
    xml-ucs-is-mongolian
    xml-ucs-is-musical-symbols
    xml-ucs-is-myanmar
    xml-ucs-is-number-forms
    xml-ucs-is-ogham
    xml-ucs-is-old-italic
    xml-ucs-is-optical-character-recognition
    xml-ucs-is-oriya
    xml-ucs-is-osmanya
    xml-ucs-is-phonetic-extensions
    xml-ucs-is-private-use
    xml-ucs-is-private-use-area
    xml-ucs-is-runic
    xml-ucs-is-shavian
    xml-ucs-is-sinhala
    xml-ucs-is-small-form-variants
    xml-ucs-is-spacing-modifier-letters
    xml-ucs-is-specials
    xml-ucs-is-superscriptsand-subscripts
    xml-ucs-is-supplemental-arrows-a
    xml-ucs-is-supplemental-arrows-b
    xml-ucs-is-supplemental-mathematical-operators
    xml-ucs-is-supplementary-private-use-area-a
    xml-ucs-is-supplementary-private-use-area-b
    xml-ucs-is-syriac
    xml-ucs-is-tagalog
    xml-ucs-is-tagbanwa
    xml-ucs-is-tags
    xml-ucs-is-tai-le
    xml-ucs-is-tai-xuan-jing-symbols
    xml-ucs-is-tamil
    xml-ucs-is-telugu
    xml-ucs-is-thaana
    xml-ucs-is-thai
    xml-ucs-is-tibetan
    xml-ucs-is-ugaritic
    xml-ucs-is-unified-canadian-aboriginal-syllabics
    xml-ucs-is-variation-selectors
    xml-ucs-is-variation-selectors-supplement
    xml-ucs-is-yi-radicals
    xml-ucs-is-yi-syllables
    xml-ucs-is-yijing-hexagram-symbols
    xml-ucs-is-block
    xml-ucs-is-cat-c
    xml-ucs-is-cat-cc
    xml-ucs-is-cat-cf
    xml-ucs-is-cat-co
    xml-ucs-is-cat-cs
    xml-ucs-is-cat-l
    xml-ucs-is-cat-ll
    xml-ucs-is-cat-lm
    xml-ucs-is-cat-lo
    xml-ucs-is-cat-lt
    xml-ucs-is-cat-lu
    xml-ucs-is-cat-m
    xml-ucs-is-cat-mc
    xml-ucs-is-cat-me
    xml-ucs-is-cat-mn
    xml-ucs-is-cat-n
    xml-ucs-is-cat-nd
    xml-ucs-is-cat-nl
    xml-ucs-is-cat-no
    xml-ucs-is-cat-p
    xml-ucs-is-cat-pc
    xml-ucs-is-cat-pd
    xml-ucs-is-cat-pe
    xml-ucs-is-cat-pf
    xml-ucs-is-cat-pi
    xml-ucs-is-cat-po
    xml-ucs-is-cat-ps
    xml-ucs-is-cat-s
    xml-ucs-is-cat-sc
    xml-ucs-is-cat-sk
    xml-ucs-is-cat-sm
    xml-ucs-is-cat-so
    xml-ucs-is-cat-z
    xml-ucs-is-cat-zl
    xml-ucs-is-cat-zp
    xml-ucs-is-cat-zs
    xml-ucs-is-cat

    ;; compile-time version informations
    xml-check-version

    ;; text writing API for XML
    xml-new-text-writer
    xml-new-text-writer-filename
    xml-new-text-writer-memory
    xml-new-text-writer-push-parser
    xml-new-text-writer-doc
    xml-new-text-writer-tree
    xml-free-text-writer
    xml-text-writer-start-document
    xml-text-writer-end-document
    xml-text-writer-start-comment
    xml-text-writer-end-comment
    xml-text-writer-write-comment
    xml-text-writer-start-element
    xml-text-writer-start-element-ns
    xml-text-writer-end-element
    xml-text-writer-full-end-element
    xml-text-writer-write-element
    xml-text-writer-write-element-ns
    xml-text-writer-write-raw-len
    xml-text-writer-write-raw
    xml-text-writer-write-string
    xml-text-writer-write-base64
    xml-text-writer-write-bin-hex
    xml-text-writer-start-attribute
    xml-text-writer-start-attribute-ns
    xml-text-writer-end-attribute
    xml-text-writer-write-attribute
    xml-text-writer-write-attribute-ns
    xml-text-writer-start-pi
    xml-text-writer-end-pi
    xml-text-writer-write-pi
    xml-text-writer-start-cdata
    xml-text-writer-end-cdata
    xml-text-writer-write-cdata
    xml-text-writer-start-dtd
    xml-text-writer-end-dtd
    xml-text-writer-write-dtd
    xml-text-writer-start-dtd-element
    xml-text-writer-end-dtd-element
    xml-text-writer-write-dtd-element
    xml-text-writer-start-dtd-attlist
    xml-text-writer-end-dtd-attlist
    xml-text-writer-write-dtd-attlist
    xml-text-writer-start-dtd-entity
    xml-text-writer-end-dtd-entity
    xml-text-writer-write-dtd-internal-entity
    xml-text-writer-write-dtd-external-entity
    xml-text-writer-write-dtd-external-entity-contents
    xml-text-writer-write-dtd-entity
    xml-text-writer-write-dtd-notation
    xml-text-writer-set-indent
    xml-text-writer-set-indent-string
    xml-text-writer-flush

    ;; XML Path Language implementation
    xml-xpath-free-object
    xml-xpath-node-set-create
    xml-xpath-free-node-set-list
    xml-xpath-free-node-set
    xml-xpath-object-copy
    xml-xpath-cmp-nodes
    xml-xpath-cast-number-to-boolean
    xml-xpath-cast-string-to-boolean
    xml-xpath-cast-node-set-to-boolean
    xml-xpath-cast-to-boolean
    xml-xpath-cast-boolean-to-number
    xml-xpath-cast-string-to-number
    xml-xpath-cast-node-to-number
    xml-xpath-cast-node-set-to-number
    xml-xpath-cast-to-number
    xml-xpath-cast-boolean-to-string
    xml-xpath-cast-number-to-string
    xml-xpath-cast-node-to-string
    xml-xpath-cast-node-set-to-string
    xml-xpath-cast-to-string
    xml-xpath-convert-boolean
    xml-xpath-convert-number
    xml-xpath-convert-string
    xml-xpath-new-context
    xml-xpath-free-context
    xml-xpath-context-set-cache
    xml-xpath-order-doc-elems
    xml-xpath-eval
    xml-xpath-eval-expression
    xml-xpath-eval-predicate
    xml-xpath-compile
    xml-xpath-ctxt-compile
    xml-xpath-compiled-eval
    xml-xpath-compiled-eval-to-boolean
    xml-xpath-free-comp-expr
    xml-xpath-init
    xml-xpath-is-nan
    xml-xpath-is-inf

    ;; API to handle XML Pointers
    xml-xptr-location-set-create
    xml-xptr-free-location-set
    xml-xptr-location-set-merge
    xml-xptr-new-range
    xml-xptr-new-range-points
    xml-xptr-new-range-node-point
    xml-xptr-new-range-point-node
    xml-xptr-new-range-nodes
    xml-xptr-new-location-set-nodes
    xml-xptr-new-location-set-node-set
    xml-xptr-new-range-node-object
    xml-xptr-new-collapsed-range
    xml-xptr-location-set-add
    xml-xptr-wrap-location-set
    xml-xptr-location-set-del
    xml-xptr-location-set-remove
    xml-xptr-new-context
    xml-xptr-eval
    xml-xptr-range-to-function
    xml-xptr-build-node-list
    xml-xptr-eval-range-predicate

    )
  (import (rnrs)
    (xml libxml2 primitives)
    (xml libxml2 sizeof)))

;;; end of file
