* nausicaa

  XXX

* lists

  Finished?

* char-set

  Finished?

* compare

  Import it.

* foreign

  Add Mosh support.

  Review the documentation.

* format

  Import the documentation from srfi.
  Finish testing, review and documentation.

* streams

  Import it.

* time

  Rewrite?

* strings

  Fix the names of the fold functions, armonising them with lists.

* vectors

  Fix the names of the fold functions, armonising them with lists.

* random

  Fix  the   generator  of  sequences   with  given  sum.    Update  the
  documentation accordingly.

  Add  the  interface to  Mersenne  Twister.   Update the  documentation
  accordingly.

  Add the Marsaglia PRNGs.  Update the documentation accordingly.

  Add a randomness source reading bytes from a given port?

  Finish port from the GSL PRNGs.

* arrays

  To be implemented taking inspiration from SRFI-25.

  Use records for  everything: array (multidimensional array), array-dim
  (dimension), array-pos (position).

* sequence

  Implement a library offering a common interface for all the sequences:
  vector, list, string, bytevectors.

* interp

  Implement the interpreters library.

