* nausicaa

  Fix the installation infrastructure (does not install directories).

* char-set

  Finished?

* compare

  Import it.

* foreign

  Import it from uriel

* format

  Import the documentation from srfi.
  Finish testing, review and documentation.

* random

  Import it.

* streams

  Import it.

* time

  Rewrite?

* strings

  Finished?

* vectors

  Finished?

* random

  Implement the jumpahead function.

  Implement the shuffle and shuffle! functions for strings and vectors.

  Implement a generic method to build real numbers from integers.

  Implement a  randomise function taking  as argument a source  of 32bit
  integers,  and internally querying  the random  source for  the needed
  number of seed values.

  Implement an utility function to  select a random element from a range
  of integers and of reals.  Support an optional step argument to select
  only multiples of the step in the range.

  Implement  an utility  function  to  select a  random  element from  a
  sequence (list, vector, string, bytevector).

  Implement  an  utility  function  "sample-population" that  returns  a
  sequence  of "len"  random  elements from  a  given sequence  (string,
  vector, list, bytevector).

* sequence

  Implement a library offering a common interface for all the sequences:
  vector, list, string, bytevectors.

