* nausicaa

  XXX

* lists

  Finished?

* char-set

  Merge the one-dimension  library into char-sets to make  it faster (it
  is too slow now).

* compare

  Import it.

* foreign

  Move the  array peeker/pokers in  the implementation compat  files and
  optimise them.

  Add Mosh support.

  Review the documentation.

  Add callbacks.

* format

  Import the documentation from srfi.
  Finish testing, review and documentation.

* streams

  Import it.

* time

  Rewrite?

* strings

  Fix the names of the fold functions, armonising them with lists.

  Implement the syntaxes for fold.

  Implement the syntaxes for map and /with-index?

* vectors

  Finished.

* random

  Implement the r250/521 PRGN from the C sources.

  Implement the Blum Blum Shub PRNG, see Wikipedia.

  Fix the generator of sequences with given sum (notice that the test in
  the  test   suite  is   commented  out).   Update   the  documentation
  accordingly.

  Add a randomness source reading bytes from a given port?

  Finish port from the GSL PRNGs.

  Port the number distributions from the GSL.

* arrays

  Finished?

* sequence

  Implement a library offering a common interface for all the sequences:
  vector, list, string, bytevectors.

* interp

  Implement the interpreters library.

* irregex

  Write a record type for the match data.

  Write a record type for the chunker.

  Remove from  the library  the code related  to UTF8  strings.  Useless
  with R6RS strings because they are sequences of Unicode code points.

  Port  the library from  the built-in  char-sets implementation  to the
  (char-sets) library.

* pregexp

  Replace calls to PREGEXP-ERROR with the appropriates error forms.

  Replace PREGEXP-REVERSE! with REVERSE! from (lists)

* scmobj

  Add usage examples for :before and :after methods.


