* documentation

  Differentiate between @meta inside normal text and @meta inside
  examples, @samp, etc.

* nausicaa

  XXX

* lists

  Finished?

* char-set

  Merge the one-dimension  library into char-sets to make  it faster (it
  is too slow now).

* compare

  Import it.

* foreign

  Move the  array peeker/pokers in  the implementation compat  files and
  optimise them.

  Add Mosh support.

  Review the documentation.

  Add callbacks.

* format

  Import the documentation from srfi.
  Finish testing, review and documentation.

* comparisons

  * Finish testing

* args-fold

  Port it from srfi to scheme projects.

* streams

  Port it from srfi to scheme projects.

* time

  Port it from srfi to scheme projects.
  Rewrite?

* strings

  Fix the names of the fold functions, armonising them with lists.

  Implement the syntaxes for fold.

  Implement the syntaxes for map and /with-index?

  Visit the following Wikipedia pages:
  http://en.wikipedia.org/wiki/Edit_distance
  http://en.wikipedia.org/wiki/Levenshtein_distance
  http://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance


* vectors

  Finished.

* random

  Implement the r250/521 PRGN from the C sources.

  Implement the Blum Blum Shub PRNG, see Wikipedia.

  Fix the generator of sequences with given sum (notice that the test in
  the  test   suite  is   commented  out).   Update   the  documentation
  accordingly.

  Add a randomness source reading bytes from a given port?

  Finish port from the GSL PRNGs.

  Port the number distributions from the GSL.

* arrays

  Finished?

* sequence

  Implement a library offering a common interface for all the sequences:
  vector, list, string, bytevectors.

* interp

  Implement the interpreters library.

* irregex

  Write a record type for the match data.

  Write a record type for the chunker.

  Remove from  the library  the code related  to UTF8  strings.  Useless
  with R6RS strings because they are sequences of Unicode code points.

  Port  the library from  the built-in  char-sets implementation  to the
  (char-sets) library.

* pregexp

  Replace calls to PREGEXP-ERROR with the appropriates error forms.

  Replace PREGEXP-REVERSE! with REVERSE! from (lists)

* scmobj

  Add usage examples for :before and :after methods.

* silex

  Done?

* lalr

  Finish documentation improvements.

* email

  Implement the (email addresses) library using (lalr).

* gcc

  Do a library  that runs GCC on files under  (by default) TMPDIR.  Make
  it compile object files and build shared libraries.

  Add functions to write a C source file from a Scheme quoted list.  The
  Scheme list  allows quasiquotation to be  used to build  the C source.
  Then just  display the list  into a string  port and trim  the parens,
  which  will be the  first and  last characters  of the  output string.
  Finally write the string to disk.

  Use the FFI to load the shared library and run the function.

