* nausicaa

  XXX

* lists

  Finished?

* char-set

  Finished?

* compare

  Import it.

* foreign

  Add Mosh support.

  Review the documentation.

* format

  Import the documentation from srfi.
  Finish testing, review and documentation.

* streams

  Import it.

* time

  Rewrite?

* strings

  Fix the names of the fold functions, armonising them with lists.

  Implement the syntaxes for fold.

  Implement the syntaxes for map and /with-index?

* vectors

  Finished.

* random

  Fix  the   generator  of  sequences   with  given  sum.    Update  the
  documentation accordingly.

  Add  the  interface to  Mersenne  Twister.   Update the  documentation
  accordingly.

  Add the Marsaglia PRNGs.  Update the documentation accordingly.

  Add a randomness source reading bytes from a given port?

  Finish port from the GSL PRNGs.

* arrays

  Finished?

* sequence

  Implement a library offering a common interface for all the sequences:
  vector, list, string, bytevectors.

* interp

  Implement the interpreters library.

* irregex

  Remove from  the library  the code related  to UTF8  strings.  Useless
  with R6RS strings because they are sequences of Unicode code points.

  Port  the library from  the built-in  char-sets implementation  to the
  (char-sets) library.

