* documentation

  Differentiate between @meta inside normal text and @meta inside
  examples, @samp, etc.

  Document  somewhere that  ypsilon requires  the --compatible  flag, or
  remove the need for --compatible.

* nausicaa

  Why I cannot install only the FASL files under ikarus?

* generics

  Profile and improve method dispatching.

* lists

  Finished(?)

* char-set

  Done.

* email

** addresses

   Scan RFC 2822 and adjust the (email addresses) library accordingly.

** headers

   Scan RFC 2822 and implement (email addresses) accordingly.

** date

   Scan RFC 2822 and implement (email date) accordingly.

* ffi

  Port all the extension packages to FFI 0.2.

* format

  Finish testing.

  Review and finish the documentation.

  Solve problems with Mosh.

  Change the interface to use the (sexps) macros to specify formatting
  parameters.

* comparisons

  * Finish testing

* times-and-dates

  Rewrite and redocument

* strings

  Fix the names of the fold functions, armonising them with lists.

  Implement the syntaxes for fold.

  Implement the syntaxes for map and /with-index?

  Visit the following Wikipedia pages:
  http://en.wikipedia.org/wiki/Edit_distance
  http://en.wikipedia.org/wiki/Levenshtein_distance
  http://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance

* vectors

  Finished.

* random

  Implement the r250/521 PRGN from the C sources.

  Add a randomness source reading bytes from a given port?

  Finish port from the GSL PRNGs?

  Port the number distributions from the GSL?

* arrays

  Finished?

* sequence

  Implement a library offering a common interface for all the sequences:
  vector, list, string, bytevectors.

* interp

  Implement the interpreters library.

* irregex

  Write a record type for the match data.

  Write a record type for the chunker.

  Remove from  the library  the code related  to UTF8  strings.  Useless
  with R6RS strings because they are sequences of Unicode code points.

  Port  the library from  the built-in  char-sets implementation  to the
  (char-sets) library.

* pregexp

  Replace calls to PREGEXP-ERROR with the appropriates error forms.

  Replace PREGEXP-REVERSE! with REVERSE! from (lists)

* scmobj

  Finished?

* silex

  Done?

* lalr

  Finished.

* gcc

  Do a library  that runs GCC on files under  (by default) TMPDIR.  Make
  it compile object files and build shared libraries.

  Add functions to write a C source file from a Scheme quoted list.  The
  Scheme list  allows quasiquotation to be  used to build  the C source.
  Then just  display the list  into a string  port and trim  the parens,
  which  will be the  first and  last characters  of the  output string.
  Finally write the string to disk.

  Use the FFI to load the shared library and run the function.

* matches

  Rewrite the OR pattern.

  Focus on destructuring bind.

* packrat

  Implement the :one and :any combinators, like the ones in (sexps).

* armor

  Add quoted-printable. http://tools.ietf.org/html/rfc2045

* libraries

  Finish the libraries inspector.

