# Makefile.begin --
#
# Common variables and rules.

#page
## ------------------------------------------------------------
## Global variables and default values.
## ------------------------------------------------------------

ifeq ($(strip TMPDIR),)
TMPDIR		= /tmp
endif

ifeq ($(strip package_BUILD_VERSION),)
package_BUILD_VERSION	= 1mm
endif

## ------------------------------------------------------------
## Binary package name variables.

# The package name will be:
#
# $(package_NAME)-$(package_VERSION)-$(package_ARCH)-$(package_BUILD_VERSION)
#
# 'package_BUILD_VERSION'     should    be     defined    in
# "Makefile.custom".

package_NAME		= $(PACKAGE)
package_VERSION		= $(VERSION)
package_ARCH		= noarch

## ------------------------------------------------------------

#page
## ------------------------------------------------------------
## Common programs.
## ------------------------------------------------------------

SED		= sed
SUDO		= sudo

## ------------------------------------------------------------

CP		= cp --force --verbose --preserve=mode --
MV		= mv --verbose --
RM		= rm --force --recursive --verbose --
RMDIR		= rmdir --parents --ignore-fail-on-non-empty --
MKDIR		= mkdir --parents --verbose

MAKEINFO	= makeinfo
TAR		= tar
BZIP2		= bzip2

## ------------------------------------------------------------

INSTALL			= install

INSTALL_DIR_MODE	= 0755
INSTALL_BIN_MODE	= 0555
INSTALL_DATA_MODE	= 0444

INSTALL_DIR		= $(INSTALL) -m $(INSTALL_DIR_MODE) -d
INSTALL_BIN		= $(INSTALL) -m $(INSTALL_BIN_MODE)
INSTALL_DATA		= $(INSTALL) -m $(INSTALL_DATA_MODE)

## ------------------------------------------------------------


### end of file
# Local Variables:
# mode: makefile
# fill-column: 60
# End:
